2017 (5)
========

#. **Bankhead, P. et al. (2017). QuPath: Open source software for digital pathology image analysis. Scientific Reports. https://doi.org/10.1038/s41598-017-17204-5**

#. Gharun, K. et al. (2017). Mycobacteria exploit nitric oxide-induced transformation of macrophages into permissive giant cells. **EMBO Reports**. https://doi.org/10.15252/embr.201744121 📙

#. Gray, R. T. et al. (2017). Evaluation of PTGS2 Expression, PIK3CA Mutation, Aspirin Use and Colon Cancer Survival in a Population-Based Cohort Study. **Clinical and Translational Gastroenterology**. https://doi.org/10.1038/ctg.2017.18 

#. Gray, R. T. et al. (2017). Statin use, candidate mevalonate pathway biomarkers, and colon cancer survival in a population-based cohort study. **British Journal of Cancer**. https://doi.org/10.1038/bjc.2017.139 

#. del Barco Barrantes, I. et al. (2017). Regulation of Mammary Luminal Cell Fate and Tumorigenesis by p38α. **Stem Cell Reports**. https://doi.org/10.1016/j.stemcr.2017.11.021 😞
