2018 (48)
=========

#. Acs, B. et al. (2018). Ki67 Reproducibility Using Digital Image Analysis : An Inter-Platform and Inter-Operator Study. **Laboratory Investigation**. https://doi.org/10.1038/s41374-018-0123-7 📗

#. Allen, W. L. et al. (2018). Transcriptional Subtyping and CD8 Immunohistochemistry Identifies Patients With Stage II and III Colorectal Cancer With Poor Prognosis Who Benefit From Adjuvant Chemotherapy. **JCO Precision Oncology**. https://doi.org/10.1200/PO.17.00241 😞

#. Avgustinova A. et al. (2018). Loss of G9a preserves mutation patterns but increases chromatin accessibility, genomic instability and aggressiveness in skin tumours. **Nature Cell Biology**. https://doi.org/10.1038/s41556-018-0233-x 😞

#. Bankhead, P. et al. (2018). Integrated tumor identification and automated scoring minimizes pathologist involvement and provides new insights to key biomarkers in breast cancer. **Laboratory Investigation**. https://doi.org/10.1038/labinvest.2017.131 

#. Bathini P. et al. (2018). Progressive signaling changes in the olfactory nerve of Alzheimer’s disease patients. **Neurobiology of Aging**. https://doi.org/10.1016/j.neurobiolaging.2018.12.006 😞

#. Bevan, R. J. et al. (2018). Meningeal inflammation and cortical demyelination in acute multiple sclerosis. **Annals of Neurology**. https://doi.org/10.1002/ana.25365 📗

#. Cagnet, S. et al. (2018). Oestrogen receptor α AF-1 and AF-2 domains have cell population-specific functions in the mammary epithelium. **Nature Communications**. https://doi.org/10.1038/s41467-018-07175-0 😞

#. Charni-Natan, M. et al. (2018). Various stress stimuli rewire the profile of liver secretome in a p53-dependent manner. **Cell Death & Disease**. https://doi.org/10.1038/s41419-018-0697-4 📗

#. Cherif-Feildel, M. et al. (2018). Morphological and molecular criteria allow the identification of putative germ stem cells in a lophotrochozoan, the Pacific oyster Crassostrea gigas. **Histochemistry and Cell Biology**. https://doi.org/10.1007/s00418-018-1740-3 📗

#. Coulson-Gilmer, C. et al. (2018). Stanniocalcin 2 expression is associated with a favourable outcome in male breast cancer. **Journal of Pathology: Clinical Research**. https://doi.org/10.1002/cjp2.106 📗

#. Cunnea, P. et al (2018). Clinical Value of Bioelectrical Properties of Cancerous Tissue in Advanced Epithelial Ovarian Cancer Patients. **Scientific Reports**. https://doi.org/10.1038/s41598-018-32720-8 📗

#. Delvaeye, T. et al. (2018). Noninvasive whole-body imaging of phosphatidylethanolamine as a cell death marker using 99m Tc-duramycin during TNF-induced SIRS. **Journal of Nuclear Medicine**. https://doi.org/10.2967/jnumed.117.205815 😞

#. Dunne, P. D. et al. (2018). Bcl-xL as a poor prognostic biomarker and predictor of response to adjuvant chemotherapy specifically in BRAF-mutant stage II and III colon cancer. **Oncotarget**. https://doi.org/10.18632/oncotarget.24481 📗

#. Fumet, J, et al. (2018). Prognostic and Predictive Role of CD8 and PD-L1 Determination in Lung Tumor Tissue of Patients under Anti-PD-1 Therapy. **British Journal of Cancer**. https://doi.org/10.1038/s41416-018-0220-9 📙

#. Garcia-Orue, I. et al. (2018). Composite nanofibrous membranes of PLGA/Aloe vera containing lipid nanoparticles for wound dressing applications. **International Journal of Pharmaceutics**. https://doi.org/10.1016/j.ijpharm.2018.12.010 😞

#. Ge, Y. et al. (2018). Alternative splice variants of DCLK1 mark cancer stem cells, promote self-renewal and drug-resistance, and can be targeted to inhibit tumorigenesis in kidney cancer. **International Journal of Cancer**. https://doi.org/10.1002/ijc.31400 📗

#. Gorlé, N. et al. (2018). The choroid plexus epithelium as a novel player in the stomach-brain axis during Helicobacter infection. **Brain, Behavior, and Immunity**. https://doi.org/10.1016/J.BBI.2017.12.010 😞

#. Graule, J. et al. (2018). CDX2 in Colorectal Cancer Is an Independent Prognostic Factor and Regulated by Promoter Methylation and Histone Deacetylation in Tumors of the Serrated Pathway. **Clinical Epigenetics**. https://doi.org/10.1186/s13148-018-0548-2 📙

#. Gray, M. E. et al. (2018). Biocompatibility of common implantable sensor materials in a tumor xenograft model. **Journal of Biomedical Materials Research Part B: Applied Biomaterials**. https://doi.org/10.1002/jbm.b.34254 😞

#. Herfs, M. et al. (2018). A dualistic model of primary anal canal adenocarcinoma with distinct cellular origins, etiologies, inflammatory microenvironments and mutational signatures: implications for personalised medicine. **British Journal of Cancer**. https://doi.org/10.1038/s41416-018-0049-2 😞

#. Humphries, M. P. et al. (2018). Critical Appraisal of Programmed Death Ligand 1 Reflex Diagnostic Testing: Current Standards and Future Opportunities. **Journal of Thoracic Oncology**. https://doi.org/10.1016/j.jtho.2018.09.025 📗

#. Huovinen, J. et al. (2018). Pharmacokinetics of intra-articular vitamin D analogue calcipotriol in sheep and metabolism in human synovial and mesenchymal stromal cells. **The Journal of Steroid Biochemistry and Molecular Biology**. https://doi.org/10.1016/j.jsbmb.2018.12.006 😞

#. Isambert, N, et al. (2018). Fluorouracil and Bevacizumab plus Anakinra for Patients with Metastatic Colorectal Cancer Refractory to Standard Therapies (IRAFU): A Single-Arm Phase 2 Study. **OncoImmunology**. https://doi.org/10.1080/2162402X.2018.1474319 😞

#. Kather, J. N. et al. (2018). Topography of cancer-associated immune cells in human solid tumors. **eLife**. https://doi.org/10.7554/eLife.36967 📗

#. Kather, J. N. et al. (2018). High-throughput screening of combinatorial immunotherapies with patient-specific in silico models of metastatic colorectal cancer. **Cancer Research**. https://doi.org/10.1158/0008-5472.CAN-18-1126 📗

#. Keller, A. et al. (2018). Prion pathogenesis is unaltered in a mouse strain with a permeable blood-brain barrier. **PLOS Pathogens**. https://doi.org/10.1371/journal.ppat.1007424 📗

#. Kim, K. et al. (2018). Androgen Deprivation Therapy Potentiates the Efficacy of Vascular Targeted Photodynamic Therapy of Prostate Cancer Xenografts. **Clinical Cancer Research**. https://doi.org/10.1158/1078-0432.CCR-17-3474 😞

#. Kriegsmann, K. et al. (2018). Combined Immunohistochemistry after Mass Spectrometry Imaging for superior spatial information. **PROTEOMICS - Clinical Applications**. https://doi.wiley.com/10.1002/prca.201800035 📗

#. Lambrechts, D. et al. (2018). Phenotype molding of stromal cells in the lung tumor microenvironment. **Nature Medicine**. https://doi.org/10.1038/s41591-018-0096-5 😞

#. Ledys, F. et al. (2018). RAS status and neoadjuvant chemotherapy impact CD8 + cells and tumor HLA class I expression in liver metastatic colorectal cancer. **Journal for ImmunoTherapy of Cancer**. https://doi.org/10.1186/s40425-018-0438-3 📗

#. Lee, S. C. W. et al. (2018). Synthetic Lethal and Convergent Biological Effects of Cancer-Associated Spliceosomal Gene Mutations. **Cancer Cell**. https://doi.org/10.1016/j.ccell.2018.07.003 😞

#. Liu, B. et al. (2018). PD-1/PD-L1 expression in a series of intracranial germinoma and its association with Foxp3+ and CD8+ infiltrating lymphocytes. **PLOS ONE**. https://doi.org/10.1371/journal.pone.0194594 📗

#. Loughrey, M. B. et al. (2018). Validation of the systematic scoring of immunohistochemically-stained tumour tissue microarrays using QuPath digital image analysis. **Histopathology**. https://doi.org/10.1111/his.13516 📗

#. Manresa-Arraut, A. et al. (2018). RhoA Drives T-Cell Activation and Encephalitogenic Potential in an Animal Model of Multiple Sclerosis. **Frontiers in Immunology**. https://doi.org/10.3389/fimmu.2018.01235 📗

#. Medfai, H. et al. (2018). Human Peroxidasin 1 Promotes Angiogenesis through ERK1/2, Akt and FAK Pathways. **Cardiovascular Research**. https://doi.org/10.1093/cvr/cvy179 😞

#. Momcilovic, M. et al. (2018). The GSK3 Signaling Axis Regulates Adaptive Glutamine Metabolism in Lung Squamous Cell Carcinoma. **Cancer Cell**. https://doi.org/10.1016/j.ccell.2018.04.002 📗

#. Näpänkangas, J. et al. (2018). Increased mesenchymal podoplanin expression is associated with calcification in aortic valves. **Cardiovascular Pathology**. https://doi.org/10.1016/j.carpath.2018.11.006 📙

#. Prall, F. & Hühns, M. (2018). Quantitative evaluation of TP53 immunohistochemistry to predict gene mutations: lessons learnt from a series of colorectal carcinomas. **Human Pathology**. https://doi.org/10.1016/j.humpath.2018.10.012 📗

#. Seyed Jafari, S. M. et al. (2018). Correlation of Vascular Endothelial Growth Factor subtypes and their receptors with melanoma progression: A next-generation Tissue Microarray (ngTMA) automated analysis. **PLOS ONE**. https://doi.org/10.1371/journal.pone.0207019 😞

#. Silva B. a. et al. (2018). A cFos activation map of remote fear memory attenuation. **Psychopharmacology**. https://doi.org/10.1007/s00213-018-5000-y 📗

#. Tauriello, D. V. F. et al. (2018). TGFβ drives immune evasion in genetically reconstituted colon cancer metastasis. **Nature**. https://doi.org/10.1038/nature25492 😞

#. Title, A. C. et al. (2018). Genetic dissection of the miR-200–Zeb1 axis reveals its importance in tumor differentiation and invasion. **Nature Communications**. https://doi.org/10.1038/s41467-018-07130-z 📗

#. Tutturen, A. E. V et al. (2018). Characterization of the small intestinal lesion in celiac disease by label-free quantitative mass spectrometry. **The American Journal of Pathology**. https://doi.org/10.1016/j.ajpath.2018.03.017 📗

#. Vesterinen, T. et al. (2018). Clinicopathological indicators of survival among patients with pulmonary carcinoid tumor. **Acta Oncologica**. https://doi.org/10.1080/0284186X.2018.1441543 📗

#. Wang, J. et al. (2018). Lysosomal acid lipase promotes cholesterol ester metabolism and drives clear cell renal cell carcinoma progression. **Cell Proliferation**. https://doi.org/10.1111/cpr.12452 😞

#. Warren, S. C. et al. (2018). Removing physiological motion from intravital and clinical functional imaging data. **eLife**. https://doi.org/10.7554/eLife.35800 📗

#. Zarella, M., & Feldscher, A. (2018). Laboratory computer performance in a digital pathology environment: Outcomes from a single institution. **Journal of Pathology Informatics**. https://doi.org/10.4103/jpi.jpi_47_18 📗

#. Zhang, A. W. et al. (2018). Interfaces of Malignant and Immunologic Clonal Dynamics in Ovarian Cancer. **Cell**. https://doi.org/10.1016/j.cell.2018.03.073 😞
