2019 (145)
==========

#. Acs, B. et al. (2019). An open source automated tumor infiltrating lymphocyte algorithm for prognosis in melanoma. **Nature Communications**. https://doi.org/10.1038/s41467-019-13043-2 📗

#. Ahtiainen, M. et al. (2019). Combined prognostic value of CD274 (PD-L1)/PDCDI (PD-1) expression and immune cell infiltration in colorectal cancer as per mismatch repair status. **Modern Pathology**. https://doi.org/10.1038/s41379-019-0219-7 📗

#. Alvim, R. G. et al. (2019). Positron Emission Tomography/Computed Tomography with Gallium-68–labeled Prostate-specific Membrane Antigen Detects Relapse After Vascular-targeted Photodynamic Therapy in a Prostate Cancer Model. **European Urology Focus**. https://doi.org/10.1016/j.euf.2019.06.008 📗

#. Alvim, R. G. et al. (2019). The potential risk of tumor progression after use of dehydrated human amnion/chorion membrane allograft in a positive margin resection model. **Therapeutic Advances in Urology**. https://doi.org/10.1177/1756287219837771 📗

#. Amaddeo, G. et al. (2019). Intra-hepatic immune changes after hepatitis c virus eradication by direct-acting antiviral therapy. **Liver International**. https://doi.org/10.1111/liv.14226 😞

#. Atif, S. M. et al. (2019). Protective role of B cells in sterile particulate-induced lung injury. **JCI Insight**. https://doi.org/10.1172/jci.insight.125494 📗

#. Balli, M. et al. (2019). Autologous micrograft accelerates endogenous wound healing response through ERK-induced cell migration. **Cell Death & Differentiation**. https://doi.org/10.1038/s41418-019-0433-3 📗

#. Barceló, C. et al. (2019). T-Type calcium channels as potential therapeutic targets in vemurafenib-resistant BRAF:sup:`V600E` melanoma: TTCCs are therapy target in BRAF:sup:`V600E` melanoma. **Journal of Investigative Dermatology**. https://doi.org/10.1016/j.jid.2019.11.014 📗

#. Bartolomé-Casado, R. et al. (2019). Resident memory CD8 T cells persist for years in human small intestine. **Journal of Experimental Medicine**. https://doi.org/10.1084/jem.20190414 📗

#. Beeler, J. S. et al. (2019). p73 regulates epidermal wound healing and induced keratinocyte programming. **PLOS ONE**. https://doi.org/10.1371/journal.pone.0218458 📗

#. Benitz, S. et al. (2019). Ring1b-dependent epigenetic remodelling is an essential prerequisite for pancreatic carcinogenesis. **Gut**. https://doi.org/10.1136/gutjnl-2018-317208 😞

#. Bhumika, S. et al. (2019). A Late Critical Period for Frequency Modulated Sweeps in the Mouse Auditory System. **Cerebral Cortex**. https://doi.org/10.1093/cercor/bhz262 😞

#. Binzer-Panchal, A. et al. (2019). Integrated Molecular Analysis of Undifferentiated Uterine Sarcomas Reveals Clinically Relevant Molecular Subtypes. **Clinical Cancer Research**. https://doi.org/10.1158/1078-0432.CCR-18-2792 📗

#. Bolli, E. et al. (2019). Stromal-targeting radioimmunotherapy mitigates the progression of therapy-resistant tumors. **Journal of Controlled Release**. https://doi.org/10.1016/j.jconrel.2019.10.024 📗

#. Bulgarelli, J. et al. (2019). Dendritic Cell Vaccination in Metastatic Melanoma Turns "Non-T Cell Inflamed” Into “T-Cell Inflamed" Tumors. **Frontiers in Immunology**. https://doi.org/10.3389/fimmu.2019.02353 📗

#. Buschmann, J. et al. (2019). Hybrid nanocomposite as a chest wall graft with improved integration by adipose-derived stem cells. **Scientific Reports**. https://doi.org/10.1038/s41598-019-47441-9 😞

#. Cai, H. et al. (2019). Cowpea Mosaic Virus Immunotherapy Combined with Cyclophosphamide Reduces Breast Cancer Tumor Burden and Inhibits Lung Metastasis. **Advanced Science**. https://doi.org/10.1002/advs.201802281 📗

#. Carter, R. et al. (2019). Exploring the potential of BH3 mimetic therapy in squamous cell carcinoma of the head and neck. **Cell Death & Disease**. https://doi.org/10.1038/s41419-019-2150-8 📗

#. Cengiz, I. F. et al. (2019). Suturable regenerated silk fibroin scaffold reinforced with 3D-printed polycaprolactone mesh: biomechanical performance and subcutaneous implantation. **Journal of Materials Science: Materials in Medicine**. https://doi.org/10.1007/s10856-019-6265-3 📗

#. Chamessian, A. et al. (2019). Is Optogenetic Activation of Vglut1-positive Aβ Low-Threshold Mechanoreceptors Sufficient to Induce Tactile Allodynia in Mice after Nerve Injury? **Journal of Neuroscience**. https://doi.org/10.1523/JNEUROSCI.2064-18.2019 📗

#. Chitty, J. L. et al. (2019). The Mini‐Organo: A rapid high‐throughput 3D coculture organotypic assay for oncology screening and drug development. **Cancer Reports**. https://doi.org/10.1002/cnr2.1209 📗

#. Chkheidze, R. et al. (2019). Distinct Expression Patterns of Carbonic Anhydrase IX in Clear Cell, Microcystic, and Angiomatous Meningiomas. **Journal of Neuropathology & Experimental Neurology**. https://doi.org/10.1093/jnen/nlz091 📗

#. Choudhury, S. R. et al. (2019). Dipeptidase-1 Is an Adhesion Receptor for Neutrophil Recruitment in Lungs and Liver. **Cell**. https://doi.org/10.1016/j.cell.2019.07.017 📗

#. Damgaard, R. B. et al. (2019). OTULIN deficiency in ORAS causes cell type‐specific LUBAC degradation, dysregulated TNF signalling and cell death. **EMBO Molecular Medicine**. https://doi.org/10.15252/emmm.201809324 📗

#. Dawson, H. et al. (2019). Tumour Budding/T‐cell infiltrates in Colorectal Cancer: Proposal of a Novel Combined Score. **Histopathology**. https://doi.org/10.1111/his.14006 📗

#. Delvaeye, T. et al. (2019). Blocking connexin43 hemichannels protects mice against tumour necrosis factor-induced inflammatory shock. **Scientific Reports**. https://doi.org/10.1038/s41598-019-52900-4 😞

#. Demontoux, L. et al. (2019). Hypotonic stress enhances colon cancer cell death induced by platinum derivatives and immunologically improves anti-tumor efficacy of intraperitoneal chemotherapy. **International Journal of Cancer**. https://doi.org/10.1002/ijc.32590 😞

#. DiStasio, M. et al. (2019). T‐lymphocytes and Cytotoxic Astrocyte Blebs Correlate Across Autism Brains. **Annals of Neurology**. https://doi.org/10.1002/ana.25610 📗

#. Dudzinski, S. O. et al. (2019). Combination immunotherapy and radiotherapy causes an abscopal treatment response in a mouse model of castration resistant prostate cancer. **Journal for ImmunoTherapy of Cancer**. https://doi.org/10.1186/s40425-019-0704-z 📗

#. Egelston, C. A. et al. (2019). Resident memory CD8:sup:`+` T cells within cancer islands mediate survival in breast cancer patients. **JCI Insight**. https://doi.org/10.1172/jci.insight.130000 📗

#. Egnell, L. et al. (2019). Stromal Collagen Content in Breast Tumors Correlates With In Vivo Diffusion‐Weighted Imaging: A Comparison of Multi b‐Value DWI With Histologic Specimen From Benign and Malignant Breast Lesions. **Journal of Magnetic Resonance Imaging**. https://doi.org/10.1002/jmri.27018 📗

#. Elmasry, M. et al. (2019). RBP7 is a clinically prognostic biomarker and linked to tumor invasion and EMT in colon cancer. **Journal of Cancer**. https://doi.org/10.7150/jca.35180 📗

#. Evans, R. et al. (2019). Integrin-Mediated Macrophage Adhesion Promotes Lymphovascular Dissemination in Breast Cancer. **Cell Reports**. https://doi.org/10.1016/j.celrep.2019.04.076 😞

#. Evrova, O. et al. (2019). Elastic and surgeon friendly electrospun tubes delivering PDGF-BB positively impact tendon rupture healing in a rabbit Achilles tendon model. **Biomaterials**. https://doi.org/10.1016/j.biomaterials.2019.119722 😞

#. Ferré, E. M. N. et al. (2019). Lymphocyte-driven regional immunopathology in pneumonitis caused by impaired central immune tolerance. **Science Translational Medicine**. https://doi.org/10.1126/scitranslmed.aav5597 📗

#. Germann, M. et al. (2019). Neutrophils suppress tumor‐infiltrating T cells in colon cancer via matrix metalloproteinase‐mediated activation of TGFβ. **EMBO Molecular Medicine**. https://doi.org/10.15252/emmm.201910681 📗

#. Giannini, L. A. A. et al. (2019). Empiric Methods to Account for Pre-analytical Variability in Digital Histopathology in Frontotemporal Lobar Degeneration. **Frontiers in Neuroscience**. https://doi.org/10.3389/fnins.2019.00682 📗

#. Gorchs, L. et al. (2019). Human Pancreatic Carcinoma-Associated Fibroblasts Promote Expression of Co-inhibitory Markers on CD4+ and CD8+ T-Cells.  **Frontiers in Immunology**. https://doi.org/10.3389/fimmu.2019.00847 📗

#. Gray, M. et al. (2019). Development and characterisation of acquired radioresistant breast cancer cell lines. **Radiation Oncology**. https://doi.org/10.1186/s13014-019-1268-2 📗

#. Gutjahr, E. & Madea, B. (2019). Inflammatory reaction patterns of the lung as a response to alveolar hypoxia and their significance for the diagnosis of asphyxiation. **Forensic Science International**. https://doi.org/10.1016/j.forsciint.2019.02.026 😞

#. Haas, Q. et al. (2019). Siglec-9 regulates an effector memory CD8+ T-cell subset that congregates in the melanoma tumor microenvironment. **Cancer Immunology Research**. https://doi.org/10.1158/2326-6066.CIR-18-0505 📗

#. Habats, R. A. et al. (2019). Safe targeting of T cell acute lymphoblastic leukemia by pathology-specific NOTCH inhibition. **Science Translational Medicine**. https://doi.org/10.1126/scitranslmed.aau6246 📗

#. Hamaidia, M. et al. (2019). Inhibition of EZH2 methyltransferase decreases immunoediting of mesothelioma cells by autologous macrophages through a PD-1–dependent mechanism. **JCI Insight**. https://doi.org/10.1172/jci.insight.128474 📗

#. Hamy, A-S. et al. (2019). Comedications influence immune infiltration and pathological response to neoadjuvant chemotherapy in breast cancer. **OncoImmunology**. https://doi.org/10.1080/2162402X.2019.1677427 📗

#. Hannen, R. et al. (2019). Comparative Transcriptomic Analysis of Temozolomide Resistant Primary GBM Stem-Like Cells and Recurrent GBM Identifies Up-Regulation of the Carbonic Anhydrase CA2 Gene as Resistance Factor. **Cancers**. https://doi.org/10.3390/cancers11070921 📗

#. Haragan, A. et al. (2019). Heterogeneity of PD-L1 expression in non-small cell lung cancer: Implications for specimen sampling in predicting treatment response. **Lung Cancer**. https://doi.org/10.1016/j.lungcan.2019.06.005 📗

#. Heichler, C. et al. (2019). STAT3 activation through IL-6/IL-11 in cancer-associated fibroblasts promotes colorectal tumour development and correlates with poor prognosis. **Gut**. https://dx.doi.org/10.1136/gutjnl-2019-319200 😞

#. Hejbøl, E. K. et al. (2019). Marker Expression of Interstitial Cells in Human Skeletal Muscle: An Immunohistochemical Study. **Journal of Histochemistry & Cytochemistry**. https://doi.org/10.1369/0022155419871033 📗

#. Hollis, R. et al. (2019). Clinical and molecular characterization of ovarian carcinoma displaying isolated lymph node relapse. **American Journal of Obstetrics & Gynecology**. https://doi.org/10.1016/j.ajog.2019.04.035 📗

#. Hossain, A. et al. (2019). Automated approach for estimation of grade groups for prostate cancer based on histological image feature analysis. **The Prostate**. https://doi.org/10.1002/pros.23943 📗

#. Hänninen, U. A. et al. (2019). Exome and immune cell score analyses reveal great variation within synchronous primary colorectal cancers. **British Journal of Cancer**. https://doi.org/10.1038/s41416-019-0427-4 📗

#. Hühns, M. et al. (2019). High mutational burden in colorectal carcinomas with monoallelic POLE mutations: absence of allelic loss and gene promoter methylation. **Modern Pathology**. https://doi.org/10.1038/s41379-019-0430-6 📗

#. Ianuş, A. et al. (2019). Higher‐order diffusion MRI characterization of mesorectal lymph nodes in rectal cancer. **Magnetic Resonance in Medicine**. https://doi.org/10.1002/mrm.28102 😞

#. Ibrahim, A. G. E. et al. (2019). Augmenting canonical Wnt signalling in therapeutically inert cells converts them into therapeutically potent exosome factories. **Nature Biomedical Engineering**. https://doi.org/10.1038/s41551-019-0448-6 😞

#. Joyeux, L. et al. (2019). Validation of the Fetal Lamb Model of Spina Bifida. **Scientific Reports**. https://doi.org/10.1038/s41598-019-45819-3 📗

#. Jung, M. et al. (2019). Prognostic Implication of pAMPK Immunohistochemical Staining by Subcellular Location and Its Association with SMAD Protein Expression in Clear Cell Renal Cell Carcinoma. **Cancers**. https://doi.org/10.3390/cancers11101602 📗

#. Jyotsana, N. (2019). Minimal dosing of leukocyte targeting TRAIL decreases triple-negative breast cancer metastasis following tumor resection. **Science Advances**. https://doi.org/10.1126/sciadv.aaw4197 😞

#. Jäkel, S. et al. (2019). Altered human oligodendrocyte heterogeneity in multiple sclerosis.  **Nature**. https://doi.org/10.1038/s41586-019-0903-2 📗

#. Kather, J. et al. (2019). CD163+ immune cell infiltrates and presence of CD54+ microvessels are prognostic markers for patients with embryonal rhabdomyosarcoma. **Scientific Reports**. https://doi.org/10.1038/s41598-019-45551-y 📗

#. Kiechle, M. et al. (2019). In Vivo Protein Complementation Demonstrates Presynaptic α-Synuclein Oligomerization and Age-Dependent Accumulation of 8–16-mer Oligomer Species. **Cell Reports**. https://doi.org/10.1016/j.celrep.2019.10.089 📗

#. Kim, Y. et al. (2019). Combination of L1 methylation and tumor-infiltrating lymphocytes as prognostic marker in advanced gastric cancer. **Gastric Cancer**. https://doi.org/10.1007/s10120-019-01025-8 📗

#. Klein, S. et al. (2019). Immune-phenotyping of pleomorphic dermal sarcomas suggests this entity as a potential candidate for immunotherapy. **Cancer Immunology, Immunotherapy**. https://doi.org/10.1007/s00262-019-02339-3 📗

#. Kulkarni, P. M. et al. (2019). Deep learning based on standard H&E images of primary melanoma tumors identifies patients at risk for visceral recurrence and death. **Clinical Cancer Research**. https://doi.org/10.1158/1078-0432.CCR-19-1495 📗

#. Lebdai, S. et al. (2019). Potentiating vascular-targeted photodynamic therapy through CSF-1R modulation of myeloid cells in a preclinical model of prostate cancer. **OncoImmunology**. https://doi.org/10.1080/2162402X.2019.1581528 😞

#. Li, A. et al. (2019). IL-33 Signaling Alters Regulatory T Cell Diversity in Support of Tumor Development. **Cell Reports**. https://doi.org/10.1016/j.celrep.2019.10.120 📗

#. Liu, K. et al. (2019). Deep learning pathological microscopic features in endemic nasopharyngeal cancer: Prognostic value and protentional role for individual induction chemotherapy. **Cancer Medicine**. https://doi.org/10.1002/cam4.2802 📗

#. Liu, M. et al. (2019). Discrimination of cervical cancer cells via cognition-based features. **Journal of Innovative Optical Health Sciences**. https://doi.org/10.1142/S1793545820500017 📗

#. Marchione, D. M. et al. (2019). Histone H3K27 dimethyl loss is highly specific for malignant peripheral nerve sheath tumor and distinguishes true PRC2 loss from isolated H3K27 trimethyl loss. **Modern Pathology**. https://doi.org/10.1038/s41379-019-0287-8 📗

#. Marshall, A. E. et al. (2019). RB1 deletion in RB-pathway disrupted cells results in DNA damage and cancer progression. **Molecular and Cellular Biology**. https://doi.org/10.1128/MCB.00105-19 📗

#. Martin, J. C. et al. (2019). Single-cell analysis of Crohn’s disease lesions identifies a pathogenic cellular module associated with resistance to anti-TNF therapy. **Cell**. https://doi.org/10.1016/j.cell.2019.08.008 📗

#. Martinez-Morilla, S. et al. (2019). Quantitative assessment of PD-L1 as an analyte in immunohistochemistry diagnostic assays using a standardized cell line tissue microarray. **Laboratory Investigation**. https://doi.org/10.1038/s41374-019-0295-9 📗

#. Michael, I. P. et al. (2019). ALK7 Signaling Manifests a Homeostatic Tissue Barrier That Is Abrogated during Tumorigenesis and Metastasis. **Developmental Cell**. https://doi.org/10.1016/j.devcel.2019.04.015 📗

#. Micossé, C. et al. (2019). Human “T\ :sub:`H`\ 9” cells are a subpopulation of PPAR-γ\ :sup:`+` T\ :sup:`H`\ 2 cells. **Science Immunology**. https://doi.org/10.1126/sciimmunol.aat5943 😞

#. Milan, M. et al. (2019). FOXA2 controls the cis‐regulatory networks of pancreatic cancer cells in a differentiation grade‐specific manner. **The EMBO Journal**. https://doi.org/10.15252/embj.2019102161 😞

#. Misra, S. et al. (2019). Ex vivo organotypic culture system of precision-cut slices of human pancreatic ductal adenocarcinoma.  **Scientific Reports**. https://doi.org/10.1038/s41598-019-38603-w 📗

#. Momcilovic, M. et al. (2019). In vivo imaging of mitochondrial membrane potential in non-small-cell lung cancer. **Nature**. https://doi.org/10.1038/s41586-019-1715-0 😞

#. Moore, P. C. et al. (2019). Parallel Signaling through IRE1α and PERK Regulates Pancreatic Neuroendocrine Tumor Growth and Survival. **Cancer Research**. https://doi.org/10.1158/0008-5472.CAN-19-1116 😞

#. Morra, F. et al. (2019). Analysis of CCDC6 as a novel biomarker for the clinical use of PARP1 inhibitors in malignant pleural mesothelioma. **Lung Cancer**. https://doi.org/10.1016/j.lungcan.2019.07.011 📗

#. Morra, F. et al. (2019). CAF-1 Subunits Levels Suggest Combined Treatments with PARP-Inhibitors and Ionizing Radiation in Advanced HNSCC. **Cancers**. https://doi.org/10.3390/cancers11101582 📗

#. Morra, F. et al. (2019). CCDC6 and USP7 expression levels suggest novel treatment options in high-grade urothelial bladder cancer.  **Journal of Experimental & Clinical Cancer Research**. https://doi.org/10.1186/s13046-019-1087-1 😞

#. Murakawa, T. et al. (2019). A Mammalian Mitophagy Receptor, Bcl2-L-13, Recruits the ULK1 Complex to Induce Mitophagy.  **Cell Reports**. https://doi.org/10.1016/j.celrep.2018.12.050 😞

#. Murray, K. et al. (2019). Functional circuitry of neuro-immune communication in the mesenteric lymph node and spleen. **Brain, Behavior, and Immunity**. https://doi.org/10.1016/j.bbi.2019.08.188 📗

#. Newell, M. et al. (2019). Comparing docosahexaenoic acid (DHA) concomitant with neoadjuvant chemotherapy versus neoadjuvant chemotherapy alone in the treatment of breast cancer (DHA WIN): protocol of a double-blind, phase II, randomised controlled trial. **BMJ Open**. https://doi.org/10.1136/bmjopen-2019-030502 📗

#. Ng, S. R. et al. (2019). CRISPR-mediated modeling and functional validation of candidate tumor suppressor genes in small cell lung cancer. **PNAS**. https://doi.org/10.1073/pnas.1821893117 📗

#. Nguyen, T. M. et al. (2019). The proportion of alveolar type 1 cells decreases in murine hypoplastic congenital diaphragmatic hernia lungs. **PLOS ONE**. https://doi.org/10.1371/journal.pone.0214793 📗

#. Nicaise, A. M. et al. (2019). Cellular senescence in progenitor cells contributes to diminished remyelination potential in progressive multiple sclerosis. **PNAS**. https://doi.org/10.1073/pnas.1818348116 📗

#. Nokin, M. et al. (2019). Methylglyoxal, a glycolysis metabolite, triggers metastasis through MEK/ERK/SMAD1 pathway activation in breast cancer. **Breast Cancer Research**. https://doi.org/10.1186/s13058-018-1095-7 😞

#. Oh, H. J. et al. (2019). p53 expression status is associated with cancer-specific survival in stage III and high-risk stage II colorectal cancer patients treated with oxaliplatin-based adjuvant chemotherapy. **British Journal of Cancer**. https://doi.org/10.1038/s41416-019-0429-2 📗

#. Onishi, A. et al. (2019). Effect of Renal Tubule-Specific Knockdown of the Na+/H+ Exchanger NHE3 in Akita Diabetic Mice. **American Journal of Physiology: Renal Physiology**. https://doi.org/10.1152/ajprenal.00497.2018 📗

#. Peralta, S. et al. (2019). Ki67 Labelling Index of Neoplastic Epithelial Cells Differentiates Canine Acanthomatous Ameloblastoma from Oral Squamous Cell Carcinoma. **Journal of Comparative Pathology**. https://doi.org/10.1016/j.jcpa.2019.08.001 📗

#. Perotti, V. et al. (2019). An actionable axis linking NFATc2 to EZH2 controls the EMT-like program of melanoma cells. **Oncogene**. https://doi.org/10.1038/s41388-019-0729-2 📗

#. Persson, E. K. et al. (2019). Protein crystallization promotes type 2 immunity and is reversible by antibody treatment. **Science**. https://doi.org/10.1126/science.aaw4295 📗

#. Piipponen, M. et al. (2019). p53-regulated long non-coding RNA PRECSIT promotes progression of cutaneous squamous cell carcinoma via STAT3 signaling. **American Journal of Pathology**. https://doi.org/10.1016/j.ajpath.2019.10.019 📗

#. Piontek, A. et al. (2019). Targeting claudin‐overexpressing thyroid and lung cancer by modified Clostridium perfringens enterotoxin. **Molecular Oncology**. https://doi.org/10.1002/1878-0261.12615 📗

#. Prasad, B. et al. (2019). Quantitative Estimation of the Equivalent Radiation Dose Escalation using Radiofrequency Hyperthermia in Mouse Xenograft Models of Human Lung Cancer. **Scientific Reports**. https://doi.org/10.1038/s41598-019-40595-6 📗

#. Prawira, A. et al. (2019). Assessment of _PARP4_ as a candidate breast cancer susceptibility gene. **Breast Cancer Research and Treatment**. https://doi.org/10.1007/s10549-019-05286-w 📗

#. Pénzváltó, Z. et al. (2019). A Syngeneic ErbB2 Mammary Cancer Model for Preclinical Immunotherapy Trials. **Journal of Mammary Gland Biology and Neoplasia**. https://doi.org/10.1007/s10911-019-09425-3 📗

#. Rafei-Shamsabad, D. et al. (2019). Successful combination therapy of systemic checkpoint inhibitors and intralesional interleukin-2 in patients with metastatic melanoma with primary therapeutic resistance to checkpoint inhibitors alone. **Cancer Immunology, Immunotherapy**. https://doi.org/10.1007/s00262-019-02377-x 📗

#. Rajendran, S. et al. (2019). IL-6 is present in beta and alpha cells in human pancreatic islets: Expression is reduced in subjects with type 1 diabetes. **Clinical Immunology**. https://doi.org/10.1016/j.clim.2019.108320 📗

#. Reed, M. D. et al. (2019). IL-17a promotes sociability in mouse models of neurodevelopmental disorders. **Nature**. https://doi.org/10.1038/s41586-019-1843-6 📗

#. Reichling, C. et al. (2019). Artificial intelligence-guided tissue analysis combined with immune infiltrate assessment predicts stage III colon cancer outcomes in PETACC08 study. **Gut**. https://dx.doi.org/10.1136/gutjnl-2019-319292 📗

#. Reiter, F. P. et al. (2019). Antifibrotic effects of hypocalcemic vitamin D analogs in murine and human hepatic stellate cells and in the CCl4 mouse model. **Laboratory Investigation**. https://doi.org/10.1038/s41374-019-0310-1 😞

#. Restrepo, P. et al. (2019). Tumoral and immune heterogeneity in an anti-PD-1 responsive glioblastoma: a case study. **Cold Spring Harbor Molecular Case Studies**. https://doi.org/10.1101/mcs.a004762 📗

#. Riolobos, L. et al. (2019). The Effect of Mouse Strain, Sex, and Carcinogen Dose on Toxicity and the Development of Lung Dysplasia and Squamous Cell Carcinomas in Mice. **Cancer Prevention Research**. https://doi.org/10.1158/1940-6207.CAPR-18-0442 📗

#. Riva, M. et al. (2019). CT-2A neurospheres-derived high-grade glioma in mice: a new model to address tumor stem cells and immunosuppression. **Biology Open**. https://doi.org/10.1242/bio.044552 📗

#. Rowe, C. W. et al. (2019). The Precursor for Nerve Growth Factor (proNGF) in Thyroid Cancer Lymph Node Metastases: Correlation with Primary Tumour and Pathological Variables. **International Journal of Molecular Sciences**. https://doi.org/10.3390/ijms20235924 📗

#. Sanghvi, A. B. et al. (2019). Performance of an artificial intelligence algorithm for reporting urine cytopathology. **Cancer Cytopathology**. https://doi.org/10.1002/cncy.22176 📗

#. Santiago, I. et al. (2019). Susceptibility perturbation MRI (SPI) maps tumor infiltration into mesorectal lymph nodes. **Cancer Research**. https://doi.org/10.1158/0008-5472.CAN-18-3682 😞

#. Sarr, A. et al. (2019). Genome-scale CRISPR/Cas9 screen determines factors modulating sensitivity to ProTide NUC-103#. **Scientific Reports**. https://doi.org/10.1038/s41598-019-44089-3 📗

#. Schürch, C. M. et al. (2019). Targeting CD47 in anaplastic thyroid carcinoma enhances tumor phagocytosis by macrophages and is a promising therapeutic strategy. **Thyroid**. https://doi.org/10.1089/thy.2018.0555 😞

#. See, T. R. et al. (2019). BAP1 Immunoreactivity Correlates with Gene Expression Class in Uveal Melanoma. **Ocular Oncology and Pathology**. https://doi.org/10.1159/000502550 😞

#. Sellmyer, M. A. et al. (2019). Imaging CAR T Cell Trafficking with eDFHR as a PET Reporter Gene. **Molecular Therapy**. https://doi.org/10.1016/j.ymthe.2019.10.007 😞

#. Sha, L. et al. (2019). Multi-field-of-view deep learning model predicts nonsmall cell lung cancer programmed death-ligand 1 status from whole-slide hematoxylin and eosin images. **Journal of Pathology Informatics**. https://doi.org/10.4103/jpi.jpi_24_19 📗

#. Steinmann, S. et al. (2019). DAPK1 loss triggers tumor invasion in colorectal tumor cells. **Cell Death & Disease**. https://doi.org/10.1038/s41419-019-2122-z 😞

#. Stålhammar, G. et al. (2019). Digital Image Analysis of BAP-1 Accurately Predicts Uveal Melanoma Metastasis. **Translational Vision Science & Technology**. https://doi.org/10.1167/tvst.8.3.11 📗

#. Stålhammar, G. et al. (2019). Expression of immune checkpoint receptors Indoleamine 2,3‐dioxygenase and T cell Ig and ITIM domain in metastatic versus nonmetastatic choroidal melanoma. **Cancer Medicine**. https://doi.org/10.1002/cam4.2167 📗

#. Suarez-Carmona, M. et al. (2019). CCR5 status and metastatic progression in colorectal cancer. **OncoImmunology**. https://doi.org/10.1080/2162402X.2019.1626193 📗

#. Sudoyo, A. W. et al. (2019). Increased CD8 Tumor Infiltrating Lymphocytes in Colorectal Cancer Microenvironment Supports an Adaptive Immune Resistance Mechanism of PD-L1 Expression. **Asian Pacific Journal of Cancer Prevention**. https://doi.org/10.31557/apjcp.2019.20.11.3421 📗

#. Tam, O. H. et al. (2019). Postmortem Cortex Samples Identify Distinct Molecular Subtypes of ALS: Retrotransposon Activation, Oxidative Stress, and Activated Glia. **Cell Reports**. https://doi.org/10.1016/j.celrep.2019.09.066 📗

#. Tsakiroglou, A. M. et al. (2019). Spatial proximity between T and PD-L1 expressing cells as a prognostic biomarker for oropharyngeal squamous cell carcinoma. **British Journal of Cancer**. https://doi.org/10.1038/s41416-019-0634-z 📗

#. Van der Merwe, J. et al. (2019). Early neuropathological and neurobehavioral consequences of preterm birth in a rabbit model. **Scientific Reports**. https://doi.org/10.1038/s41598-019-39922-8 📗

#. Van der Veeken, L. et al. (2019). Long-term neurological effects of neonatal caffeine treatment in a rabbit model of preterm birth. **Pediatric Research**. https://doi.org/10.1038/s41390-019-0718-8 📗

#. Van der Veeken, L. et al. (2019). Maternal surgery during pregnancy has a transient adverse effect on the developing fetal rabbit brain. **American Journal of Obstetrics and Gynecology**. https://doi.org/10.1016/j.ajog.2019.07.029 📗

#. Varricchio, C. et al. (2019). The ying and yang of idebenone: Not too little, not too much – cell death in NQO1 deficient cells and the mouse retina. **Free Radical Biology and Medicine**. https://doi.org/10.1016/j.freeradbiomed.2019.11.030 📗

#. Vassileva, V. et al. (2019). Evaluation of apoptosis imaging biomarkers in a genetic model of cell death. **EJNMMI Research**. https://doi.org/10.1186/s13550-019-0487-8 📗

#. Vaupel, P. et al. (2019). The Warburg effect: Essential part of metabolic reprogramming and central contributor to cancer progression. **International Journal of Radiation Biology**. https://doi.org/10.1080/09553002.2019.1589653 📗

#. Vennin, C. et al. (2019). CAF hierarchy driven by pancreatic cancer cell p53-status creates a pro-metastatic and chemoresistant environment via perlecan. **Nature Communications**. https://doi.org/10.1038/s41467-019-10968-6 😞

#. Vesterinen, T. et al. (2019). PD-1 and PD-L1 expression in pulmonary carcinoid tumors and their association to tumor spread. **Endocrine Connections**. https://doi.org/10.1530/EC-19-0308 📗

#. Vuono, R. et al. (2019). Association Between Toll‐Like Receptor 4 (TLR4) and Triggering Receptor Expressed on Myeloid Cells 2 (TREM2) Genetic Variants and Clinical Progression of Huntington's Disease. **Movement Disorders**. https://doi.org/10.1002/mds.27911 📗

#. Wang, Z. et al. (2019). Syngeneic animal models of tobacco-associated oral cancer reveal the activity of in situ anti-CTLA-4. **Nature Communications**. https://doi.org/10.1038/s41467-019-13471-0 📗

#. Welz, P-S. et al. (2019). BMAL1-Driven Tissue Clocks Respond Independently to Light to Maintain Homeostasis. **Cell**. https://doi.org/10.1016/j.cell.2019.05.009 📗

#. Williams, L. et al. (2019). N-acetylcysteine resolves placental inflammatory-vasculopathic changes in mice consuming a high fat diet. **American Journal of Pathology**. https://doi.org/10.1016/j.ajpath.2019.07.010 😞

#. Wu, C. et al. (2019). Prognostic Immune Cell Profiling of Malignant Pleural Effusion Patients by Computerized Immunohistochemical and Transcriptional Analysis. **Cancers**. https://doi.org/10.3390/cancers11121953 📗

#. Wu, E. K. et al. (2019). TNF-Induced Interstitial Lung Disease in a Murine Arthritis Model: Accumulation of Activated Monocytes, Conventional Dendritic Cells, and CD21+/CD23− B Cell Follicles Is Prevented with Anti-TNF Therapy. **Journal of Immunology**. https://doi.org/10.4049/jimmunol.1900473 😞

#. Wu, R-C. et al. (2019). Identification of the PTEN-ARID4B-PI3K pathway reveals the dependency on ARID4B by PTEN-deficient prostate cancer. **Nature Communications**. https://doi.org/10.1038/s41467-019-12184-8 📗

#. Xia, R. et al. (2019). Diagnosis of Liver Neoplasms by Computational and Statistical Image Analysis. **Gastroenterology Research**. https://doi.org/10.14740/gr1210 📗

#. Yao, J. et al. (2019). Metabolic characterization of human IDH mutant and wild type gliomas using simultaneous pH- and oxygen-sensitive molecular MRI. **Neuro-Oncology**. https://doi.org/10.1093/neuonc/noz078 📗

#. Yoo, S-Y. et al. (2019). Clinicopathological Characterization and Prognostic Implication of SMAD4 Expression in Colorectal Carcinoma. **Journal of Pathology and Translational Medicine**. https://doi.org/10.4132/jptm.2019.06.07 📗

#. Yoo, S-Y. et al. (2019). Whole-slide image analysis reveals quantitative landscape of tumor-immune microenvironment in colorectal cancers. **Clinical Cancer Research**. https://doi.org/10.1158/1078-0432.CCR-19-1159 📗

#. Zhand, S. et al. (2019). A digital pathology-based shotgun-proteomics approach to biomarker discovery in colorectal cancer. **Journal of Pathology Informatics**. https://doi.org/10.4103/jpi.jpi_65_18 📗

#. Zhang, X-J. et al. (2019). Angiocrine Hgf signaling controls physiologic organ and body size and dynamic hepatocyte proliferation to prevent liver damage during regeneration. **The American Journal of Pathology**. https://doi.org/10.1016/j.ajpath.2019.10.009 📗

#. Zhang, Y. et al. (2019). Mutant IDH sensitizes gliomas to endoplasmic reticulum stress and triggers apoptosis via microRNA183-mediated inhibition of Semaphorin 3E. **Cancer Research**. https://doi.org/10.1158/0008-5472.CAN-19-0054 📗

#. Zúñiga, W. C. et al. (2019). Raman Spectroscopy for Rapid Evaluation of Surgical Margins during Breast Cancer Lumpectomy. **Scientific Reports**. https://doi.org/10.1038/s41598-019-51112-0 😞

#. del-Pozo, J. et al. (2019). Chronic otitis media is initiated by a bulla cavitation defect in the FBXO11 mouse model.  **Disease Models & Mechanisms**. https://doi.org/10.1242/dmm.038315 📗

#. del-Pozo, J. et al. (2019). Role of ectodysplasin signalling in middle ear and nasal pathology in rat and mouse models of hypohidrotic ectodermal dysplasia. **Disease Models & Mechanisms**. https://doi.org/10.1242/dmm.037804 📗
