2020 (265)
==========

#. Abdullahi Sidi, F. et al. (2020). PD-L1 Multiplex and Quantitative Image Analysis for Molecular Diagnostics. **Cancers**. https://doi.org/10.3390/cancers13010029 📗

#. Abengozar-Muela, M. et al. (2020). Diverse immune environments in human lung tuberculosis granulomas assessed by quantitative multiplexed immunofluorescence. **Modern Pathology**. https://doi.org/10.1038/s41379-020-0600-6 📗

#. Aguanno, D. et al. (2020). The intestinal quorum sensing 3-oxo-C12:2 Acyl homoserine lactone limits cytokine-induced tight junction disruption. **Tissue Barriers**. https://doi.org/10.1080/21688370.2020.1832877 📗

#. Ansermet, C. et al. (2020). Renal tubular Arginase‐2 participates in the formation of the corticomedullary urea gradient and attenuates kidney damage in ischemia‐reperfusion injury in mice. **Acta Physiologica**. https://doi.org/10.1111/apha.13457 😞

#. April-Monn, S. L. et al. (2020). 3D Primary Cell Culture: A Novel Preclinical Model For Pancreatic Neuroendocrine Tumors (PanNETs). **Neuroendocrinology**. https://doi.org/10.1159/000507669 📗

#. Arafah, K. et al. (2020). Microproteomics and Immunohistochemistry Reveal Differences in Aldo‐Keto Reductase Family 1 Member C3 (AKR1C3) in Tissue Specimens of Ulcerative Colitis and Crohn's Disease. **Proteomics: Clinical Applications**. https://doi.org/10.1002/prca.201900110 📗

#. Ardali, R. et al. (2020). Pathophysiological role of Atg5 in human ulcerative colitis. **Intestinal Research**. https://doi.org/10.5217/ir.2019.00120 😞

#. Ataca, D. et al. (2020). The secreted protease Adamts18 links hormone action to activation of the mammary stem cell niche. **Nature Communications**. https://doi.org/10.1038/s41467-020-15357-y 😞

#. Balancin, M. L. et al. (2020). An integrative histopathologic clustering model based on immuno‐matrix elements to predict the risk of death in malignant mesothelioma. **Cancer Medicine**. https://doi.org/10.1002/cam4.3111 📗

#. Banville, A. C. et al. (2020). Co-expression patterns of chimeric antigen receptor (CAR)-T cell target antigens in primary and recurrent ovarian cancer. **Gynecologic Oncology**. https://doi.org/10.1016/j.ygyno.2020.12.005 😞

#. Bartolomé-Casado, R. et al. (2020). CD4+ T cells persist for years in the human small intestine and display a TH1 cytokine profile. **Mucosal Immunology**. https://doi.org/10.1038/s41385-020-0315-5 📗

#. Bayram, J. et al. (2020). Cytotoxicity of the effector protein BteA was attenuated in Bordetella pertussis by insertion of an alanine residue. **PLoS Pathogens**. https://doi.org/10.1371/journal.ppat.1008512 📗

#. Beck, O. et al. (2020). Safety and Activity of the Combination of Ceritinib and Dasatinib in Osteosarcoma. **Cancers**. https://doi.org/10.3390/cancers12040793 📗

#. Bell, A. M. et al. (2020). Expression of green fluorescent protein defines a specific population of lamina II excitatory interneurons in the GRP::eGFP mouse. **Scientific Reports**. https://doi.org/10.1038/s41598-020-69711-7 😞

#. Belluco, S. et al. (2020). FOXP3, CD208, and CD206 Expression in Canine Cutaneous Histiocytoma. **Veterinary Pathology**. https://doi.org/10.1177/0300985820941818 📗

#. Berben, L. et al. (2020). Computerized scoring protocol for identification and quantification of different immune cell populations in breast tumor regions using QuPath software. **Histopathology**. https://doi.org/10.1111/his.14108 📗

#. Berger, S. et al. (2020). Severe hydroxymethylbilane synthase deficiency causes depression-like behavior and mitochondrial dysfunction in a mouse model of homozygous dominant acute intermittent porphyria. **Acta Neuropathologica Communications**. https://doi.org/10.1186/s40478-020-00910-z 📗

#. Bezemer, R. E. et al. (2020). Altered Levels of Decidual Immune Cell Subsets in Fetal Growth Restriction, Stillbirth, and Placental Pathology. **Frontiers in Immunology**. https://doi.org/10.3389/fimmu.2020.01898 📗

#. Blagih, J. et al. (2020). Cancer-Specific Loss of p53 Leads to a Modulation of Myeloid and T Cell Responses. **Cell Reports**. https://doi.org/10.1016/j.celrep.2019.12.028 📗

#. Blajan, I. et al. (2020). Comprehensive Analysis of the ATP-binding Cassette Subfamily B Across Renal Cancers Identifies ABCB8 Overexpression in Phenotypically Aggressive Clear Cell Renal Cell Carcinoma. **European Urology Focus**. https://doi.org/10.1016/j.euf.2020.09.007 📗

#. Bolm, L. et al. (2020). Alignment of stroma fibers, microvessel density and immune cell populations determine overall survival in pancreatic cancer—An analysis of stromal morphology. **PLOS ONE**. https://doi.org/10.1371/journal.pone.0234568 📗

#. Boustani, J. et al. (2020). Radiotherapy Scheme Effect on PD-L1 Expression for Locally Advanced Rectal Cancer. **Cells**. https://doi.org/10.3390/cells9092071 📗

#. Bouteldja, N. et al. (2020). Deep Learning–Based Segmentation and Quantification in Experimental Kidney Histopathology. **Journal of the American Society of Nephrology**. https://doi.org/10.1681/ASN.2020050597 📗

#. Braun, F. et al. (2020). The proteomic landscape of small urinary extracellular vesicles during kidney transplantation. **Journal of Extracellular Vesicles**. https://doi.org/10.1002/jev2.12026 📗

#. Brial, F. et al. (2020). The Natural Metabolite 4-Cresol Improves Glucose Homeostasis and Enhances β-Cell Function. **Cell Reports**. https://doi.org/10.1016/j.celrep.2020.01.066 😞

#. Bruyere, D. et al. (2020). Treatment algorithm and prognostic factors for patients with stage I–III carcinoma of the anal canal: a 20-year multicenter study. **Modern Pathology**. https://doi.org/10.1038/s41379-020-0637-6 📗

#. Bulle, A. et al. (2020). Gemcitabine Recruits M2-Type Tumor-Associated Macrophages into the Stroma of Pancreatic Cancer. **Translational Oncology**. https://doi.org/10.1016/j.tranon.2020.01.004 📗

#. Caruana, D. et al. (2020). Association between low estrogen receptor positive breast cancer and staining performance. **npj Breast Cancer**. https://doi.org/10.1038/s41523-020-0146-2 📗

#. Cascalho, A. et al. (2020). Excess Lipin enzyme activity contributes to TOR1A recessive disease and DYT-TOR1A dystonia. **Brain**. https://doi.org/10.1093/brain/awaa139 😞

#. Cazettes, F. et al. (2020). Phasic Activation of Dorsal Raphe Serotonergic Neurons Increases Pupil Size. **Current Biology**. https://doi.org/10.1016/j.cub.2020.09.090 📗

#. Cengiz, I. F. et al. (2020). Entrapped in cage (EiC) scaffolds of 3D-printed polycaprolactone and porous silk fibroin for meniscus tissue engineering. **Biofabrication**. https://doi.org/10.1088/1758-5090/ab779f 📗

#. Challoner, B. R. et al. (2020). Computational image analysis of T-cell infiltrates in resectable gastric cancer: association with survival and molecular subtypes. **Journal of the National Cancer Institute**. https://doi.org/10.1093/jnci/djaa051 📗

#. Chatzopoulos, K. et al. (2020). Transcriptomic and Immunophenotypic Characterization of Tumor Immune Microenvironment in Squamous Cell Carcinoma of the Oral Tongue. **Head and Neck Pathology**. https://doi.org/10.1007/s12105-020-01229-w 📗

#. Chaursiya, S. et al. (2020). Oncolytic poxvirus CF33-hNIS-ΔF14.5 favorably modulates tumor immune microenvironment and works synergistically with anti-PD-L1 antibody in a triple-negative breast cancer model. **OncoImmunology**. https://doi.org/10.1080/2162402X.2020.1729300 😞

#. Chen, W-T. et al. (2020). Spatial Transcriptomics and In Situ Sequencing to Study Alzheimer’s Disease. **Cell**. https://doi.org/10.1016/j.cell.2020.06.038 📗

#. Chou, M. et al. (2020). Optimization of an automated tumor-infiltrating lymphocyte algorithm for improved prognostication in primary melanoma. **Modern Pathology**. https://doi.org/10.1038/s41379-020-00686-6 📗

#. Chung, G. et al. (2020). Persistent Activity of Metabotropic Glutamate Receptor 5 in the Periaqueductal Gray Constrains Emergence of Chronic Neuropathic Pain. **Current Biology**. https://doi.org/10.1016/j.cub.2020.09.008 📗

#. Chung, K. M. et al. (2020). Endocrine-Exocrine Signaling Drives Obesity-Associated Pancreatic Ductal Adenocarcinoma. **Cell**. https://doi.org/10.1016/j.cell.2020.03.062 😞

#. Clé, M. et al. (2020). Study of Usutu virus neuropathogenicity in mice and human cellular models. **PLOS Neglected Tropical Diseases**. https://doi.org/10.1371/journal.pntd.0008223 😞

#. Coelho, R. et al. (2020). Regulation of invasion and peritoneal dissemination of ovarian cancer by mesothelin manipulation. **Oncogenesis**. https://doi.org/10.1038/s41389-020-00246-2 😞

#. Concat, C. et al. (2020). Combined deletion of Glut1 and Glut3 impairs lung adenocarcinoma growth. **eLife**. https://doi.org/10.7554/eLife.53618 📗

#. Coope, R. J. N. et al. (2020). Whole‐slide laser microdissection for tumour enrichment. **Journal of Pathology**. https://doi.org/10.1002/path.5575 📗

#. Crawford, L. J. et al. (2020). The E3 ligase HUWE1 inhibition as a therapeutic strategy to target MYC in multiple myeloma. **Oncogene**. https://doi.org/10.1038/s41388-020-1345-x 📗

#. Cummings, M. et al. (2020). Decreasing formalin concentration improves quality of DNA extracted from formalin-fixed paraffin-embedded tissue specimens without compromising tissue morphology or immunohistochemical staining. **Journal of Clinical Pathology**. https://dx.doi.org/10.1136/jclinpath-2019-206368 📗

#. D'Anna, F. et al. (2020). DNA methylation repels binding of hypoxia-inducible transcription factors to maintain tumor immunotolerance. **Genome Biology**. https://doi.org/10.1186/s13059-020-02087-z 😞

#. Decker, J. T. et al. (2020). Cyclin E overexpression confers resistance to trastuzumab through noncanonical phosphorylation of SMAD3 in HER2+ breast cancer. **Cancer Biology & Therapy**. https://doi.org/10.1080/15384047.2020.1818518 📗

#. Deman, F. et al. (2020). Assessment of stromal tumor infiltrating lymphocytes and immunohistochemical features in invasive micropapillary breast carcinoma with long-term outcomes. **Breast Cancer Research and Treatment**. https://doi.org/10.1007/s10549-020-05913-x 📗

#. Dheilly, E. et al. (2020). Cathepsin S Regulates Antigen Processing and T Cell Activity in Non-Hodgkin Lymphoma. **Cancer Cell**. https://doi.org/10.1016/j.ccell.2020.03.016 😞

#. Dorward, D. A. et al. (2020). Tissue-specific Immunopathology in Fatal COVID-19. **American Journal of Respiratory and Critical Care Medicine**. https://doi.org/10.1164/rccm.202008-3265oc 📗

#. Dzaparidze, G. et al. (2020). The decline of FANCM immunohistochemical expression in prostate cancer stroma correlates with the grade group. **Pathology International**. https://doi.org/10.1111/pin.12953 📗

#. Echle, A. et al. (2020). Clinical-grade Detection of Microsatellite Instability in Colorectal Tumors by Deep Learning. **Gastroenterology**. https://doi.org/10.1053/j.gastro.2020.06.021 📗

#. El Kazzi, M. et al. (2020). Nitroxides Mitigate Neutrophil-Mediated Damage to the Myocardium after Experimental Myocardial Infarction in Rats. **International Journal of Molecular Sciences**. https://doi.org/10.3390/ijms21207650 😞

#. Elsherbini D. M. et al. (2020). Effect of meloxicam (cyclooygenase-2 inhibitor) versus vitamin D3 (cholecalciferol) as ameliorating agents of progressive doxorubicin-induced nephrotoxicity in rats. **Anatomy & Cell Biology**. https://doi.org/10.5115/acb.19.231 📗

#. Eshed-Eisenbach, Y. et al. (2020). Precise Spatiotemporal Control of Nodal Na+ Channel Clustering by Bone Morphogenetic Protein-1/Tolloid-like Proteinases. **Neuron**. https://doi.org/10.1016/j.neuron.2020.03.001 📗

#. Eskiocak, U. et al. (2020). Differentiated agonistic antibody targeting CD137 eradicates large tumors without hepatotoxicity. **JCI Insight**. https://doi.org/10.1172/jci.insight.133647 😞

#. Fagerland, S-M. T. et al. (2020). Ultrasound-Mediated Delivery of Chemotherapy into the Transgenic Adenocarcinoma of the Mouse Prostate Model. **Ultrasound in Medicine & Biology**. https://doi.org/10.1016/j.ultrasmedbio.2020.07.004 📗

#. Fahr, L. et al. (2020). Expression of the *EWSR1-FLI1* fusion oncogene in pancreas cells drives pancreatic atrophy and lipomatosis. **Pancreatology**. https://doi.org/10.1016/j.pan.2020.10.033 😞

#. Feinauer, M. J. et al. (2020). Local blood coagulation drives cancer cell arrest and brain metastasis in a mouse model. **Blood**. https://doi.org/10.1182/blood.2020005710 📗

#. Fercoq, F. et al. (2020). Microfilaria-dependent thoracic pathology associated with eosinophilic and fibrotic polyps in filaria-infected rodents. **Parasites & Vectors**. https://doi.org/10.1186/s13071-020-04428-0 📗

#. Finney, C. A. et al. (2020). A scalable, fully automated approach for regional quantification of immunohistochemical staining of astrocytes in the rat brain. **Journal of Neuroscience Methods**. https://doi.org/10.1016/j.jneumeth.2020.108994 📗

#. Frangež, Z. et al. (2020). BIF-1 inhibits both mitochondrial and glycolytic ATP production: its downregulation promotes melanoma growth. **Oncogene**. https://doi.org/10.1038/s41388-020-1339-8 📗

#. Frangež, Ž. et al. (2020). Loss of Concurrent Regulation of the Expression of BIF-1, BAX, and Beclin-1 in Primary and Metastatic Melanoma. **Biochemistry (Moscow)**. https://doi.org/10.1134/S0006297920100107 📗

#. Friedman, G. et al. (2020). Cancer-associated fibroblast compositions change with breast cancer progression linking the ratio of S100A4+ and PDPN+ CAFs to clinical outcome. **Nature Cancer**. https://doi.org/10.1038/s43018-020-0082-y 📗

#. Gao, W. et al. (2020). Targeting SKA3 suppresses the proliferation and chemoresistance of laryngeal squamous cell carcinoma via impairing PLK1–AKT axis-mediated glycolysis. **Cell Death & Disease**. https://doi.org/10.1038/s41419-020-03104-6 😞

#. George-Jones, N. A. (2020). MRI Texture Features are Associated with Vestibular Schwannoma Histology. **The Laryngoscope**. https://doi.org/10.1002/lary.29309 📗

#. Georges, N. D. R. et al. (2020). Tumour budding and CD8+ T‐cells: “attackers” and “defenders” in rectal cancer with and without neoadjuvant chemoradiotherapy. **Histopathology**. https://doi.org/10.1111/his.14319 📗

#. Ghasemi, F. et al. (2020). High MHC-II expression in Epstein–Barr virus-associated gastric cancers suggests that tumor cells serve an important role in antigen presentation. **Scientific Reports**. https://doi.org/10.1038/s41598-020-71775-4 📗

#. Gil, K. N. et al. (2020). Rorqual whale nasal plugs: protecting the respiratory tract against water entry and barotrauma. **Journal of Experimental Biology**. https://doi.org/10.1242/jeb.219691 📗

#. Gilardi, M. et al. (2020). Tipifarnib as a Precision Therapy for HRAS-Mutant Head and Neck Squamous Cell Carcinomas. **Molecular Cancer Therapeutics**. https://doi.org/10.1158/1535-7163.MCT-19-0958 😞

#. Gillich, A. et al. (2020). Capillary cell-type specialization in the alveolus. **Nature**. https://doi.org/10.1038/s41586-020-2822-7 📗

#. Gitto, S. B. et al. (2020). Identification of a novel IL-5 signaling pathway in chronic pancreatitis and crosstalk with pancreatic tumor cells. **Cell Communication and Signaling**. https://doi.org/10.1186/s12964-020-00594-x 📗

#. Glaeser, J. D. et al. (2020). Optimization of a rat lumbar IVD degeneration model for low back pain. **JOR Spine**. https://doi.org/10.1002/jsp2.1092 😞

#. Gonzalez, D. et al. (2020). Feasibility of a Deep Learning Algorithm to Distinguish Large Cell Neuroendocrine from Small Cell Lung Carcinoma in Cytology Specimens. **Cytopathology**. https://doi.org/10.1111/cyt.12829 😞

#. Goto, Y. et al. (2020). Muscarinic receptors promote castration-resistant growth of prostate cancer through a FAK–YAP signaling axis. **Oncogene**. https://doi.org/10.1038/s41388-020-1272-x 📗

#. Gruber, T. et al. (2020). IL-32γ potentiates tumor immunity in melanoma. **JCI Insight**. https://doi.org/10.1172/jci.insight.138772 📗

#. Guadagno, A. et al. (2020). It is all in the right amygdala: increased synaptic plasticity and perineuronal nets in male, but not female juvenile rat pups after exposure to early-life stress. **Journal of Neuroscience**. https://doi.org/10.1523/JNEUROSCI.1029-20.2020 😞

#. Gualandi, M. et al. (2020). Oncogenic ALK:sup:`F1174L` drives tumorigenesis in cutaneous squamous cell carcinoma. **Life Science Alliance**. https://dx.doi.org/10.26508/lsa.201900601 📗

#. Gullo, I. et al. (2020). The Dysfunctional Immune System in Common Variable Immunodeficiency Increases the Susceptibility to Gastric Cancer. **Cells**. https://doi.org/10.3390/cells9061498 📗

#. Gupta, S. et al. (2020). Digital quantitative assessment of PD-L1 using digital spatial profiling. **Laboratory Investigation**. https://doi.org/10.1038/s41374-020-0424-5 📗

#. Haasnoot, K. J. C. et al. (2020). Associations of non-pedunculated T1 colorectal adenocarcinoma outcome with consensus molecular subtypes, immunoscore, and microsatellite status: a multicenter case-cohort study. **Modern Pathology**. https://doi.org/10.1038/s41379-020-0598-9 📗

#. Hameed, Z. et al. (2020). Breast Cancer Histopathology Image Classification Using an Ensemble of Deep Learning Models. **Sensors**. https://doi.org/10.3390/s20164373 📗

#. Hases, L. et al. (2020). High-fat diet and estrogen impacts the colon and its transcriptome in a sex-dependent manner. **Scientific Reports**. https://doi.org/10.1038/s41598-020-73166-1 😞

#. Hayward, M-K. et al. (2020). Derivation of a nuclear heterogeneity image index to grade DCIS. **Computational and Structural Biotechnology Journal**. https://doi.org/10.1016/j.csbj.2020.11.040 📗

#. He, Z. et al. (2020). Loss of the proprotein convertase _Furin_ in T cells represses mammary tumorigenesis in oncogene-driven triple negative breast cancer. **Cancer Letters**. https://doi.org/10.1016/j.canlet.2020.05.001 😞

#. Hecht, M. et al. (2020). Safety and efficacy of single cycle induction treatment with cisplatin/docetaxel/ durvalumab/tremelimumab in locally advanced HNSCC: first results of CheckRad-CD8. **Journal for ImmunoTherapy of Cancer**. http://dx.doi.org/10.1136/jitc-2020-001378 📗

#. Herrspiegel, C. et al. (2020). Digital morphometry of tumor nuclei correlates to BAP-1 status, monosomy 3, gene expression class and survival in uveal melanoma. **Experimental Eye Research**. https://doi.org/10.1016/j.exer.2020.107987 📗

#. Hewitt, G. et al. (2020). Defective ALC1 nucleosome remodeling confers PARPi sensitization and synthetic lethality with HRD. **Molecular Cell**. https://doi.org/10.1016/j.molcel.2020.12.006 📗

#. Hodgson, A. et al. (2020). Suppression of ovarian hormones in adolescent rats has no effect on anxiety‐like behaviour or c‐fos activation in the amygdala. **Journal of Endocrinology**. https://doi.org/10.1111/jne.12897 📗

#. Holczer, M. et al. (2020). Fine-tuning of AMPK–ULK1–mTORC1 regulatory triangle is crucial for autophagy oscillation. **Scientific Reports**. https://doi.org/10.1038/s41598-020-75030-8 😞

#. Hornsby, A. K. E. et al. (2020). Unacylated-Ghrelin Impairs Hippocampal Neurogenesis and Memory in Mice and Is Altered in Parkinson’s Dementia in Humans. **Cell Reports Medicine**. https://doi.org/10.1016/j.xcrm.2020.100120 📗

#. Huang, A. Y-S. et al. (2020). Region-Specific Transcriptional Control of Astrocyte Function Oversees Local Circuit Activities. **Neuron**. https://doi.org/10.1016/j.neuron.2020.03.025 📗

#. Hudeček, J. et al. (2020). Application of a risk-management framework for integration of stromal tumor-infiltrating lymphocytes in clinical trials. **npj Breast Cancer**. https://doi.org/10.1038/s41523-020-0155-1 📗

#. Hughes, K. et al. (2020). Proliferation of HIV-infected renal epithelial cells following virus acquisition from infected macrophages. **AIDS**. https://doi.org/10.1097/QAD.0000000000002589 📗

#. Humphries, M. P. et al. (2020). Improving the Diagnostic Accuracy of the PD-L1 Test with Image Analysis and Multiplex Hybridization. **Cancers**. https://doi.org/10.3390/cancers12051114 📗

#. Humphries, M. P. et al. (2020). The adaptive immune and immune checkpoint landscape of neoadjuvant treated esophageal adenocarcinoma using digital pathology quantitation. **BMC Cancer**. https://doi.org/10.1186/s12885-020-06987-y 📗

#. Jiang, J. et al. (2020). Image-to-image translation for automatic ink removal in whole slide images. **Journal of Medical Imaging**. https://doi.org/10.1117/1.JMI.7.5.057502 📗

#. Julià, A. et al. (2020). Lower peripheral helper T cell levels in the synovium are associated with a better response to anti-TNF therapy in rheumatoid arthritis. **Arthritis Research & Therapy**. https://doi.org/10.1186/s13075-020-02287-9 📗

#. Jung, M. et al. (2020). CK14 Expression Identifies a Basal/Squamous-Like Type of Papillary Non-Muscle-Invasive Upper Tract Urothelial Carcinoma. **Frontiers in Oncology**. https://doi.org/10.3389/fonc.2020.00623 📗

#. Jung, M. et al. (2020). Non-Muscle-Invasive Bladder Carcinoma with Respect to Basal Versus Luminal Keratin Expression. **International Journal of Molecular Sciences**. https://doi.org/10.3390/ijms21207726 📗

#. Jung, S. et al. (2020). Seizure-induced neuronal apoptosis is related to dysregulation of the RNA-edited GluR2 subunit in the developing mouse brain. **Brain Research**. https://doi.org/10.1016/j.brainres.2020.146760 😞

#. Junttila, A. et al. (2020). Immunophenotype based on inflammatory cells, PD-1/PD-L1 signalling pathway and M2 macrophages predicts survival in gastric cancer. **British Journal of Cancer**. https://doi.org/10.1038/s41416-020-01053-7 😞

#. Jäntti, T. et al. (2020). Characterization of immunoreactivity with whole-slide imaging and digital analysis in high-grade serous ovarian cancer. **Tumor Biology**. https://doi.org/10.1177/1010428320971404 📗

#. Kaalund, S. S. et al. (2020). Locus coeruleus pathology in progressive supranuclear palsy, and its relation to disease severity. **Acta Neuropathologica Communications**. https://doi.org/10.1186/s40478-020-0886-0 😞

#. Kalish, B. T. et al. (2020). Single-nucleus RNA sequencing of mouse auditory cortex reveals critical period triggers and brakes. **PNAS**. https://doi.org/10.1073/pnas.1920433117 📗

#. Karkampouna, S. et al. (2020). Stroma Transcriptomic and Proteomic Profile of Prostate Cancer Metastasis Xenograft Models Reveals Prognostic Value of Stroma Signatures. **Cancers**. https://doi.org/10.3390/cancers12123786 📗

#. Karn, T. et al. (2020). A small hypoxia signature predicted pCR response to bevacizumab in the neoadjuvant GeparQuinto breast cancer trial. **Clinical Cancer Research**. https://doi.org/10.1158/1078-0432.CCR-19-1954 📗

#. Kather, J. et al. (2020). Pan-cancer image-based detection of clinically actionable genetic alterations. **Nature Cancer**. https://doi.org/10.1038/s43018-020-0087-6 📗

#. Kelly, L. et al. (2020). Increased Hypothalamic Projections to the Lateral Hypothalamus and Responses to Leptin in Rat Neonates From High Fat Fed Mothers. **Frontiers in Neuroscience**. https://doi.org/10.3389/fnins.2019.01454 📗

#. Kemi, N. et al. (2020). Immune Cell Infiltrate and Prognosis in Gastric Cancer. **Cancers**. https://doi.org/10.3390/cancers12123604 📗

#. Kendall, T. J. et al. (2020). Integration of geoscience frameworks into digital pathology analysis permits quantification of microarchitectural relationships in histological landscapes. **Scientific Reports**. https://doi.org/10.1038/s41598-020-74691-9 📗

#. Kenney, H. M. et al. (2020). Lineage tracing reveals evidence of a popliteal lymphatic muscle progenitor cell that is distinct from skeletal and vascular muscle progenitors. **Scientific Reports**. https://doi.org/10.1038/s41598-020-75190-7 📗

#. Kerby, A. et al. (2020). Placental Morphology and Cellular Characteristics in Stillbirths in Women With Diabetes and Unexplained Stillbirths. **Archives of Pathology & Laboratory Medicine**. https://doi.org/10.5858/arpa.2019-0524-OA 📗

#. Kesar, N. et al. (2020). Prognostic impact of CD8-positive tumour-infiltrating lymphocytes and PD-L1 expression in salivary gland cancer. **Oral Oncology**. https://doi.org/10.1016/j.oraloncology.2020.104931 📗

#. Kilvaer, T. K. et al. (2020). Digitally Quantified CD8+ Cells – The Best Candidate Marker for an Immune Cell Score in NSCLC? **Carcinogenesis**. https://doi.org/10.1093/carcin/bgaa105 📗

#. Kim, J. H. et al. (2020). Multi-Spheroid-Loaded Human Acellular Dermal Matrix Carrier Preserves Its Spheroid Shape and Improves In Vivo Adipose-Derived Stem Cell Delivery and Engraftment. **Tissue Engineering and Regenerative Medicine**. https://doi.org/10.1007/s13770-020-00252-w 📗

#. Kim, Y. et al. (2020). Protein Expression in Metastatic Melanoma and the Link to Disease Presentation in a Range of Tumor Phenotypes. **Cancers**. https://doi.org/10.3390/cancers12030767 📗

#. Kim, Y. et al. (2020). Identification and Validation of VEGFR2 Kinase as a Target of Voacangine by a Systematic Combination of DARTS and MSI. **Biomolecules**. https://doi.org/10.3390/biom10040508 📗

#. Klümper, N. et al. (2020). Downstream neighbor of SON (DONSON) is associated with unfavorable survival across diverse cancers with oncogenic properties in clear cell renal cell carcinoma. **Translational Oncology**. https://doi.org/10.1016/j.tranon.2020.100844 📗

#. Kretschmer, T. et al. (2020). Maternal high fat diet-induced obesity affects trophoblast differentiation and placental function in mice. **Biology of Reproduction**. https://doi.org/10.1093/biolre/ioaa166 😞

#. Kriegsmann, M. et al. (2020). Deep Learning for the Classification of Small-Cell and Non-Small-Cell Lung Cancer. **Cancers**. https://doi.org/10.3390/cancers12061604 😞

#. Kubach, J. et al. (2020). Same same but different: A Web‐based deep learning application revealed classifying features for the histopathologic distinction of cortical malformations. **Epilepsia**. https://doi.org/10.1111/epi.16447 📗

#. Kurppa, K. J. et al. (2020). Treatment-Induced Tumor Dormancy through YAP-Mediated Transcriptional Reprogramming of the Apoptotic Pathway. **Cancer Cell**. https://doi.org/10.1016/j.ccell.2019.12.006 📗

#. LaFave, L. M. et al. (2020). Epigenomic State Transitions Characterize Tumor Progression in Mouse Lung Adenocarcinoma. **Cancer Cell**. https://doi.org/10.1016/j.ccell.2020.06.006 📗

#. Laville, D. et al. (2020). Immune Escape Is an Early Event in Pre-Invasive Lesions of Lung Squamous Cell Carcinoma. **Diagnostics**. https://doi.org/10.3390/diagnostics10070503 😞

#. Lee, J.A. et al. (2020). Differential immune microenvironmental features of microsatellite-unstable colorectal cancers according to Fusobacterium nucleatum status. **Cancer Immunology, Immunotherapy**. https://doi.org/10.1007/s00262-020-02657-x 📗

#. Lee, K. et al. (2020). _Proline rich 11 (PRR11)_ overexpression amplifies PI3K signaling and promotes antiestrogen resistance in breast cancer. **Nature Communications**. https://doi.org/10.1038/s41467-020-19291-x 📗

#. Li, B. et al. (2020). Single image super-resolution for whole slide image using convolutional neural networks and self-supervised color normalization. **Medical Image Analysis**. https://doi.org/10.1016/j.media.2020.101938 📗

#. Li, Q. et al. (2020). Anti-PD-1 antibody-mediated activation of type 17 T-cells undermines checkpoint blockade therapy. **Cancer Immunology, Immunotherapy**. https://doi.org/10.1007/s00262-020-02795-2 😞

#. Liot, S. et al. (2020). Loss of Tenascin-X expression during tumor progression: A new pan-cancer marker. **Matrix Biology Plus**. https://doi.org/10.1016/j.mbplus.2020.100021 😞

#. Liu, B. et al. (2020). Mutant SF3B1 promotes AKT and NF-kB driven mammary tumorigenesis. **Journal of Clinical Investigation**. https://doi.org/10.1172/JCI138315 📗

#. Liu, C-H. et al. (2020). Nodal β spectrins are required to maintain Na+ channel clustering and axon integrity. **eLife**. https://doi.org/10.7554/eLife.52378.sa1 📗

#. Liu, J. Y. W. et al. (2020). Granule Cell Dispersion in Human Temporal Lobe Epilepsy: Proteomics Investigation of Neurodevelopmental Migratory Pathways. **Frontiers in Cellular Neuroscience**. https://doi.org/10.3389/fncel.2020.00053 📗

#. Liu, Y. et al. (2020). TSP1‐CD47‐SIRPα signaling facilitates the development of endometriosis by mediating the survival of ectopic endometrium. **American Journal of Reproductive Immunology**. https://doi.org/10.1111/aji.13236 📗

#. Loughrey, M. et al. (2020). Identifying mismatch repair deficient colon cancer: near perfect concordance between immunohistochemistry and microsatellite instability testing in a large, population-based series. **Histopathology**. https://doi.org/10.1111/his.14233 📗

#. Lucchesi, D. et al. (2020). Impaired IL‐27 Mediated Control of CD4+ T Cell Function Impacts on Ectopic Lymphoid Structure Formation in Patients with Sjögren's Syndrome. **Arthritis & Rheumatology**. https://doi.org/10.1002/art.41289 📗

#. Luszczak, S. et al. (2020). Co-targeting PIM and PI3K/mTOR using multikinase inhibitor AUM302 and a combination of AZD-1208 and BEZ235 in prostate cancer. **Scientific Reports**. https://doi.org/10.1038/s41598-020-71263-9 😞

#. Maguire, A. S. et al. (2020). Whole-slide image analysis outperforms micrograph acquisition for adipocyte size quantification. **Adipocyte**. https://doi.org/10.1080/21623945.2020.1823139 📗

#. Mandal, R. K. et al. (2020). Temporospatial shifts within commercial laboratory mouse gut microbiota impact experimental reproducibility. **BMC Biology**. https://doi.org/10.1186/s12915-020-00810-7 📗

#. Mannix, R. et al. (2020). Internal jugular vein compression collar mitigates histopathological alterations after closed head rotational head impact in swine: A pilot study. **Neuroscience**. https://doi.org/10.1016/j.neuroscience.2020.04.009 😞

#. Marcelis, L. et al. (2020). In-depth characterization of the tumor microenvironment in central nervous system lymphoma reveals implications for immune-checkpoint therapy. **Cancer Immunology, Immunotherapy**. https://doi.org/10.1007/s00262-020-02575-y 📗

#. Marino, N. et al. (2020). Upregulation of lipid metabolism genes in the breast prior to cancer diagnosis. **npj Breast Cancer**. https://doi.org/10.1038/s41523-020-00191-8 📗

#. Marotte, L. et al. (2020). Increased antitumor efficacy of PD-1-deficient melanoma-specific human lymphocytes. **Journal for ImmunoTherapy of Cancer**. http://dx.doi.org/10.1136/jitc-2019-000311 📗

#. Martino, F. et al. (2020). A Machine-learning Approach for the Assessment of the Proliferative Compartment of Solid Tumors on Hematoxylin-Eosin-Stained Sections. **Cancers**. https://doi.org/10.3390/cancers12051344 📗

#. Mast, N. et al. (2020). CYP46A1-dependent and independent effects of efavirenz treatment. **Brain Communications**. https://doi.org/10.1093/braincomms/fcaa180 📗

#. Mayer, A. et al. (2020). Role of Hypoxia and the Adenosine System in Immune Evasion and Prognosis of Patients with Brain Metastases of Melanoma: A Multiplex Whole Slide Immunofluorescence Study. **Cancers**. https://doi.org/10.3390/cancers12123753 📗

#. McBurney-Lin, J. et al. (2020). Bidirectional pharmacological perturbations of the noradrenergic system differentially affect tactile detection. **Neuropharmacology**. https://doi.org/10.1016/j.neuropharm.2020.108151 📗

#. McLeod, R. et al. (2020). First-in-human study of AT13148, a dual ROCK-AKT inhibitor in patients with solid tumors. **Clinical Cancer Research**. https://doi.org/10.1158/1078-0432.CCR-20-0700 📗

#. Meran, L. et al. (2020). Engineering transplantable jejunal mucosal grafts using patient-derived organoids from children with intestinal failure. **Nature Medicine**. https://doi.org/10.1038/s41591-020-1024-z 📗

#. Merritt, C. R. et al. (2020). Multiplex digital spatial profiling of proteins and RNA in fixed tissue. **Nature Biotechnology**. https://doi.org/10.1038/s41587-020-0472-9 😞

#. Milan, M. et al. (2020). Pancreatic Cancer Cells Require the Transcription Factor MYRF to Maintain ER Homeostasis. **Developmental Cell**. https://doi.org/10.1016/j.devcel.2020.09.011 📗

#. Miles, G. J. et al. (2020). Evaluating and comparing immunostaining and computational methods for spatial profiling of drug response in patient-derived explants. **Laboratory Investigation**. https://doi.org/10.1038/s41374-020-00511-3 📗

#. Millar, E. K. A. et al. (2020). Tumour Stroma Ratio Assessment Using Digital Image Analysis Predicts Survival in Triple Negative and Luminal Breast Cancer. **Cancers**. https://doi.org/10.3390/cancers12123749 📗

#. Milne, E. et al. (2020). Cytological and microbiological characteristics of middle ear effusions in brachycephalic dogs. **Journal of Veterinary Internal Medicine**. https://doi.org/10.1111/jvim.15792 📗

#. Mohanty, A. et al. (2020). A Non-genetic Mechanism Involving the Integrin β4/Paxillin Axis Contributes to Chemoresistance in Lung Cancer. **iScience**. https://doi.org/10.1016/j.isci.2020.101496 📗

#. Molitor, D. C. A. et al. (2020). Macrophage frequency in the bone marrow correlates with morphologic subtype of myeloproliferative neoplasm. **Annals of Hematology**. https://doi.org/10.1007/s00277-020-04304-y 📗

#. Moreira-Teixeira, L. et al. (2020). Type I IFN exacerbates disease in tuberculosis-susceptible mice by inducing neutrophil-mediated lung inflammation and NETosis. **Nature Communications**. https://doi.org/10.1038/s41467-020-19412-6 📗

#. Morral, C. et al. (2020). Zonation of Ribosomal DNA Transcription Defines a Stem Cell Hierarchy in Colorectal Cancer. **Cell Stem Cell**. https://doi.org/10.1016/j.stem.2020.04.012 😞

#. Morriss, N. J. et al. (2020). Automated quantification of immunohistochemical staining of large animal brain tissue using QuPath software. **Neuroscience**. https://doi.org/10.1016/j.neuroscience.2020.01.006 📗

#. Moyano‐Galceran, L. et al. (2020). Adaptive RSK‐EphA2‐GPRC5A signaling switch triggers chemotherapy resistance in ovarian cancer. **EMBO Molecular Medicine**. https://doi.org/10.15252/emmm.201911177 📗

#. Mulvaney, E. P. et al. (2020). Efficacy of the thromboxane receptor antagonist _NTP42_ alone, or in combination with sildenafil, in the sugen/hypoxia-induced model of pulmonary arterial hypertension. **European Journal of Pharmacology**. https://doi.org/10.1016/j.ejphar.2020.173658 📗

#. Mulvaney, E. et al. (2020). NTP42, a novel antagonist of the thromboxane receptor, attenuates experimentally induced pulmonary arterial hypertension. **BMC Pulmonary Medicine**. https://dx.doi.org/10.21203/rs.2.18445/v4 📗

#. Mustofa, et al. (2020). Polyherbal formula (ASILACT®) induces Milk production in lactating rats through Upregulation of α-Lactalbumin and aquaporin expression. **MBC Complementary Medicine and Therapies**. https://doi.org/10.1186/s12906-020-03152-7 😞

#. Muthalagu, N. et al. (2020). Repression of the Type I Interferon pathway underlies MYC & KRAS-dependent evasion of NK & B cells in Pancreatic Ductal Adenocarcinoma. **Cancer Discovery**. http://doi.org/10.1158/2159-8290.CD-19-0620 😞

#. Mysona, B. A. et al. (2020). QuPath Automated Analysis of Optic Nerve Degeneration in Brown Norway Rats. **Translational Vision Science & Technology**. https://doi.org/10.1167/tvst.9.3.22 📗

#. Nair-Menon, J. et al. (2020). Predominant Distribution of the RNAi Machinery at Apical Adherens Junctions in Colonic Epithelia Is Disrupted in Cancer. **International Journal of Molecular Sciences**. https://doi.org/10.3390/ijms21072559 📗

#. Naughton, M. et al. (2020). CCN3 is dynamically regulated by treatment and disease state in multiple sclerosis. **Journal of Neuroinflammation**. https://doi.org/10.1186/s12974-020-02025-7 📗

#. Nejman, D. et al. (2020). The human tumor microbiome is composed of tumor type–specific intracellular bacteria. **Science**. https://doi.org/10.1126/science.aay9189 📗

#. Nerviani, A. et al. (2020). IL-23 skin and joint profiling in psoriatic arthritis: novel perspectives in understanding clinical responses to IL-23 inhibitors. **Annals of the Rheumatic Diseases**. http://dx.doi.org/10.1136/annrheumdis-2020-218186 📗

#. Ng, S. S. et al. (2020). The NK cell granule protein NKG7 regulates cytotoxic granule exocytosis and inflammation. **Nature Immunology**. https://doi.org/10.1038/s41590-020-0758-6 😞

#. Nikitin, P. V. et al. (2020). Identification of different cell clusters in the endothelium of atherosclerotic vessels and determination of inter-cluster gradient of proliferative and inflammatory activity as new diagnostic markers. **Biotechnic & Histochemistry**. https://doi.org/10.1080/10520295.2020.1823016 📗

#. Nolan, M. et al. (2020). Quantitative patterns of motor cortex proteinopathy across ALS genotypes. **Acta Neuropathologica Communications**. https://doi.org/10.1186/s40478-020-00961-2 📗

#. Norberg, K. J. et al. (2020). A novel pancreatic tumour and stellate cell 3D co-culture spheroid model. **BMC Cancer**. https://doi.org/10.1186/s12885-020-06867-5 📗

#. Oberbeck, S. et al. (2020). Non-canonical effector functions of the T-memory-like T-PLL cell are shaped by cooperative TCL1A and TCR signaling. **Blood**. https://doi.org/10.1182/blood.2019003348 📗

#. Oh, J. H. (2020). Elevated GCN5 expression confers tamoxifen resistance by upregulating AIB1 expression in ER-positive breast cancer. **Cancer Letters**. https://doi.org/10.1016/j.canlet.2020.09.017 😞

#. Ohm, D. T. et al. (2020). Degeneration of the locus coeruleus is a common feature of tauopathies and distinct from TDP-43 proteinopathies in the frontotemporal lobar degeneration spectrum. **Acta Neuropathologica**. https://doi.org/10.1007/s00401-020-02210-1 😞

#. Okudela, K. et al. (2020). A method to obtain reproducible Ki‐67 indexes in lung adenocarcinoma. **Histopathology**. https://doi.org/10.1111/his.14234 📗

#. Orgaz, J. L. et al. (2020). Myosin II Reactivation and Cytoskeletal Remodeling as a Hallmark and a Vulnerability in Melanoma Therapy Resistance. **Cancer Cell**. https://doi.org/10.1016/j.ccell.2019.12.003 📗

#. Ottley, E. C. et al. (2020). Greater utility of molecular subtype rather than epithelial‐to‐mesenchymal transition (EMT) markers for prognosis in high‐risk non‐muscle‐invasive (HGT1) bladder cancer. **Journal of Pathology: Clinical Research**. https://doi.org/10.1002/cjp2.167 📗

#. Oulès, B. et al. (2020). Contribution of GATA6 to homeostasis of the human upper pilosebaceous unit and acne pathogenesis. **Nature Communications**. https://doi.org/10.1038/s41467-020-18784-z 😞

#. Owens, R. et al. (2020). Comparison of different anti‐Ki67 antibody clones and hot‐spot sizes for assessing proliferative index and grading in pancreatic neuroendocrine tumours using manual and image analysis. **Histopathology**. https://doi.org/10.1111/his.14200 📗

#. Park, J. A. et al. (2020). GD2 or HER2 targeting T cell engaging bispecific antibodies to treat osteosarcoma. **Journal of Hematology & Oncology**. https://doi.org/10.1186/s13045-020-01012-y 😞

#. Patel, K. S. et al. (2020). Decorin expression is associated with predictive diffusion MR phenotypes of anti-VEGF efficacy in glioblastoma. **Scientific Reports**. https://doi.org/10.1038/s41598-020-71799-w 📗

#. Peluso, M. O. et al. (2020). The Fully human anti-CD47 antibody SRF231 exerts dual-mechanism antitumor activity via engagement of the activating receptor CD32a. **Journal for Immunotherapy of Cancer**. https://doi.org/10.1136/jitc-2019-000413 📗

#. Picard, M. et al. (2020). Ileal immune tonus is a prognosis marker of proximal colon cancer in mice and patients. **Cell Death & Differentiation**. https://doi.org/10.1038/s41418-020-00684-w 📗

#. Pilot, T. et al. (2020). Heat shock and HSP70 regulate 5-FU-mediated caspase-1 activation in myeloid-derived suppressor cells and tumor growth in mice. **Journal for ImmunoTherapy of Cancer**. http://dx.doi.org/10.1136/jitc-2019-000478 😞

#. Pires, A. et al. (2020). Immune Remodelling of the Extracellular Matrix Drives Loss of Cancer Stem Cells and Tumor Rejection. **Cancer Immunology Research**. http://doi.org/10.1158/2326-6066.CIR-20-0070 📗

#. Plekhanov, A. A. et al. (2020). Histological validation of in vivo assessment of cancer tissue inhomogeneity and automated morphological segmentation enabled by Optical Coherence Elastography. **Scientific Reports**. https://doi.org/10.1038/s41598-020-68631-w 📗

#. Portman, N. et al. (2020). MDM2 inhibition in combination with endocrine therapy and CDK4/6 inhibition for the treatment of ER-positive breast cancer. **Breast Cancer Research**. https://doi.org/10.1186/s13058-020-01318-2 😞

#. Prieto‐Garcia, C. et al. (2020). Maintaining protein stability of ∆Np63 via USP28 is required by squamous cancer cells. **EMBO Molecular Medicine**. https://doi.org/10.15252/emmm.201911101 📗

#. Puladi, B. et al. (2020). The relation between tau pathology and granulovacuolar degeneration of neurons. **Neurobiology of Disease**. https://doi.org/10.1016/j.nbd.2020.105138 📗

#. Pulsawatdi, A. V. et al. (2020). A robust multiplex immunofluorescence and digital pathology workflow for the characterisation of the tumour immune microenvironment. **Molecular Oncology**. https://doi.org/10.1002/1878-0261.12764 📗

#. Rajakumar, S. A. et al. (2020). B cell acute lymphoblastic leukemia cells mediate RANK-RANKL–dependent bone destruction. **Science Translational Medicine**. https://doi.org/10.1126/scitranslmed.aba5942 📗

#. Ramos, C. V. et al. (2020). Cell Competition, the Kinetics of Thymopoiesis, and Thymus Cellularity Are Regulated by DoubleNegative 2 to 3 Early Thymocytes. **Cell Reports**. https://doi.org/10.1016/j.celrep.2020.107910 📗

#. Raposo, T. P. et al. (2020). Tensin4 (TNS4) is upregulated by Wnt signalling in adenomas in multiple intestinal neoplasia (Min) mice. **International Journal of Experimental Pathology**. https://doi.org/10.1111/iep.12352 😞

#. Rasmussen, J. H. et al. (2020). Does multiparametric imaging with 18F-FDG-PET/MRI capture spatial variation in immunohistochemical cancer biomarkers in head and neck squamous cell carcinoma? **British Journal of Cancer**. https://doi.org/10.1038/s41416-020-0876-9 📗

#. Remmerie, A. et al. (2020). Osteopontin Expression Identifies a Subset of Recruited Macrophages Distinct from Kupffer Cells in the Fatty Liver. **Immunity**. https://doi.org/10.1016/j.immuni.2020.08.004 📗

#. Roberti, M. P. et al. (2020). Chemotherapy-induced ileal crypt apoptosis and the ileal microbiome shape immunosurveillance and prognosis of proximal colon cancer. **Nature Medicine**. https://doi.org/10.1038/s41591-020-0882-8 📗

#. Robertson, S. et al. (2020). Prognostic potential of automated Ki67 evaluation in breast cancer: different hot spot definitions versus true global score. **Breast Cancer Research and Treatment**. https://doi.org/10.1007/s10549-020-05752-w 📗

#. Rodriguez-Hernandez, I. et al. (2020). WNT11-FZD7-DAAM1 signalling supports tumour initiating abilities and melanoma amoeboid invasion. **Nature Communications**. https://doi.org/10.1038/s41467-020-18951-2 📗

#. Roelofs, A. J. (2020). Identification of the skeletal progenitor cells forming osteophytes in osteoarthritis. **Osteoarthritis**. https://doi.org/10.1136/annrheumdis-2020-218350 📗

#. Roider, T. et al. (2020). Dissecting intratumour heterogeneity of nodal B-cell lymphomas at the transcriptional, genetic and drug-response levels. **Nature Cell Biology**. https://doi.org/10.1038/s41556-020-0532-x 📗

#. Romero, J. M. et al. (2020). A four-chemokine signature is associated with a T cell-inflamed phenotype in primary and metastatic pancreatic cancer. **Clinical Cancer Research**. https://doi.org/10.1158/1078-0432.CCR-19-2803 📗

#. Roszkowiak, L. et al. (2020). Clustered nuclei splitting based on recurrent distance transform in digital pathology images. **EURASIP Journal on Image and Video Processing**. https://doi.org/10.1186/s13640-020-00514-6 📗

#. Rowe, C. W. et al. (2020). Innervation of papillary thyroid cancer and its association with extra-thyroidal invasion. **Scientific Reports**. https://doi.org/10.1038/s41598-020-58425-5 📗

#. Rubey, M. et al. (2020). DLL1- and DLL4-Mediated Notch Signaling is Essential for Adult Pancreatic Islet Homeostasis. **Diabetes**. https://doi.org/10.2337/db19-0795 📗

#. Russo, D. et al. (2020). Expression of P16INK4a in Uveal Melanoma: New Perspectives. **Frontiers in Oncology**. https://doi.org/10.3389/fonc.2020.562074 📗

#. Safari, H. et al. (2020). Biodegradable, bile salt microparticles forlocalized fat dissolution. **Science Advances**. https://doi.org/10.1126/sciadv.abd8019 😞

#. Safari, R. et al. (2020). Ablation of non-coding RNAs affects bovine leukemia virus B lymphocyte proliferation and abrogates oncogenesis. **PLoS Pathogens**. https://doi.org/10.1371/journal.ppat.1008502 😞

#. Saleh, R. et al. (2020). Differential gene expression of tumor-infiltrating CD8+ T cells in advanced versus early-stage colorectal cancer and identification of a gene signature of poor prognosis. **Journal for ImmunoTherapy of Cancer**. http://dx.doi.org/10.1136/jitc-2020-001294 📗

#. Saliakoura, M. et al. (2020). PLCγ1 suppression promotes the adaptation of KRAS-mutant lung adenocarcinomas to hypoxia. **Nature Cell Biology**. https://doi.org/10.1038/s41556-020-00592-8 😞

#. Samueli, B. et al. (2020). Remote pathology education during the COVID-19 era: Crisis converted to opportunity. **Annals of Diagnostic Pathology**. https://doi.org/10.1016/j.anndiagpath.2020.151612 😞

#. Sarma, J. D. et al. (2020). Ifit2 deficiency restricts microglial activation and leukocyte migration following murine coronavirus (m-CoV) CNS infection. **PLOS Pathogens**. https://doi.org/10.1371/journal.ppat.1009034 📗

#. Schmauch, B. et al. (2020). A deep learning model to predict RNA-Seq expression of tumours from whole slide images. **Nature Communications**. https://doi.org/10.1038/s41467-020-17678-4 📗

#. Schottlaender, L. V. et al. (2020). Bi-allelic JAM2 Variants Lead to Early-Onset Recessive Primary Familial Brain Calcification. **AJHG**. https://doi.org/10.1016/j.ajhg.2020.02.007 😞

#. Sebastiano, M. R. et al. (2020). ACSL3–PAI-1 signaling axis mediates tumor-stroma cross-talk promoting pancreatic cancer progression. **Science Advances**. https://doi.org/10.1126/sciadv.abb9200 😞

#. Semba, T. et al. (2020). Lung Adenocarcinoma Mouse Models Based on Orthotopic Transplantation of Syngeneic Tumor-Initiating Cells Expressing EpCAM, SCA-1, and Ly6d. **Cancers**. https://doi.org/10.3390/cancers12123805 📗

#. Seok, J. Y. et al. (2020). TROP-2, 5hmC, and IDH1 Expression in Anaplastic Thyroid Carcinoma. **International Journal of Surgical Pathology**. https://doi.org/10.1177/1066896920978597 📗

#. Sharps, M. C. et al. (2020). Increased Placental Macrophages and a Pro‐inflammatory Profile in Placentas and Maternal Serum in Infants with a Decreased Growth Rate in the Third Trimester of Pregnancy. **American Journal of Reproductive Immunology**. https://doi.org/10.1111/aji.13267 😞

#. Shawer, H. et al. (2020). A missense mutation of ErbB2 produces a novel mouse model of stillbirth associated with a cardiac abnormality but lacking abnormalities of placental structure. **PLOS ONE**. https://doi.org/10.1371/journal.pone.0233007 📗

#. Shochet, G. E. et al. (2020). Galectin-3 levels are elevated following nintedanib treatment. **Therapeutic Advances in Chronic Disease**. https://doi.org/10.1177/2040622320968412 📗

#. Shochet, G. E. et al. (2020). Integrin alpha-5 silencing leads to myofibroblastic differentiation in IPF-derived human lung fibroblasts. **Therapeutic Advances in Chronic Disease**. https://doi.org/10.1177/2040622320936023 📗

#. Sidi, F. A. et al. (2020). PD-L1 Multiplex and Quantitative Image Analysis for Molecular Diagnostics. **Cancers**. https://doi.org/10.3390/cancers13010029 📗

#. Siersbaek, R. et al. (2020). IL6/STAT3 Signaling Hijacks Estrogen Receptor α Enhancers to Drive Breast Cancer Metastasis. **Cancer Cell**. https://doi.org/10.1016/j.ccell.2020.06.007 📗

#. Sieviläinen, M. et al. (2020). Evaluation Challenges in the Validation of B7-H3 as Oral Tongue Cancer Prognosticator. **Head and Neck Pathology**. https://doi.org/10.1007/s12105-020-01222-3 📗

#. Sirotkina, M. A. et al. (2020). In vivo assessment of functional and morphological alterations in tumors under treatment using OCT-angiography combined with OCT-elastography. **Biomedical Optics Express**. https://doi.org/10.1364/BOE.386419 😞

#. Song, K. Y. et al. (2020). Correlation of MET and PD-L1 Expression in Malignant Melanoma. **Cancers**. https://doi.org/10.3390/cancers12071847 📗

#. Sparkenbaugh, E. M. et al. (2020). High molecular weight kininogen contributes to early mortality and kidney dysfunction in a mouse model of sickle cell disease. **Journal of Thrombosis and Haemostasis**. https://doi.org/10.1111/jth.14972 😞

#. Starkl, P. et al. (2020). IgE Effector Mechanisms, in Concert with Mast Cells, Contribute to Acquired Host Defense against *Staphylococcus aureus*. **Immunity**. https://doi.org/10.1016/j.immuni.2020.08.002 📗

#. Stranahan, L. W. et al. (2020). Evaluation of the Efficacy of the *Brucella canis* RM6/66 ΔvjbR Vaccine Candidate for Protection against B. _canis_ Infection in Mice. **mSphere**. https://doi.org/10.1128/mSphere.00172-20 📗

#. Stępniewski, J. et al. (2020). Human Induced Pluripotent Stem Cell-Derived Cardiomyocytes, in Contrast to Adipose Tissue-Derived Stromal Cells, Efficiently Improve Heart Function in Murine Model of Myocardial Infarction. **Biomedicines**. https://doi.org/10.3390/biomedicines8120578 📗

#. Swiderska-Chadaj, Z. et al. (2020). Impact of rescanning and normalization on convolutional neural network performance in multi-center, whole-slide classification of prostate cancer. **Scientific Reports**. https://doi.org/10.1038/s41598-020-71420-0 📗

#. Talbot, J. et al. (2020). Feeding-dependent VIP neuron–ILC3 circuit regulates the intestinal barrier. **Nature**. https://doi.org/10.1038/s41586-020-2039-9 📗

#. Tedeschi, A. et al. (2020). Cep55 promotes cytokinesis of neural progenitors but is dispensable for most mammalian cell divisions. **Nature Communications**. https://doi.org/10.1038/s41467-020-15359-w 📗

#. Tiwari, L. et al. (2020). Clinico‐pathological correlation of optical fluorescence imaging in oral mucosal lesions. **Oral Diseases**. https://doi.org/10.1111/odi.13334 📗

#. Tkachev, S. Y. et al. (2020). Visualization of different anatomical parts of the enucleated human eye using X-ray micro-CT imaging. **Experimental Eye Research**. https://doi.org/10.1016/j.exer.2020.108394 📗

#. Tratwal, J. et al. (2020). _MarrowQuant_ Across Aging and Aplasia: A Digital Pathology Workflow for Quantification of Bone Marrow Compartments in Histological Sections. **Frontiers in Endocrinology**. https://doi.org/10.3389/fendo.2020.00480 📗

#. Tsunoda, Y. et al. (2020). Expression level of long noncoding RNA H19 of normotensive placentas in late pregnancy relates to the fetal growth restriction. **Journal of Obstetrics and Gynaecology Research**. https://doi.org/10.1111/jog.14260 📗

#. Tuominen, S. et al. (2020). Evaluation of [18F]F-DPA as a target for TSPO in head and neck cancer under normal conditions and after radiotherapy. **European Journal of Nuclear Medicine and Molecular Imaging**. https://doi.org/10.1007/s00259-020-05115-z 📗

#. Van Gils, N. et al. (2020). IGFBP7 activates retinoid acid–induced responses in acute myeloid leukemia stem and progenitor cells. **Blood Advances**. https://doi.org/10.1182/bloodadvances.2020002812 😞

#. Van Looveren, K. et al. (2020). Glucocorticoids limit lipopolysaccharide‐induced lethal inflammation by a double control system. **EMBO Reports**. https://doi.org/10.15252/embr.201949762 😞

#. Varea, O. et al. (2020). Suppression of glycogen synthesis as a treatment for Lafora disease: Establishing the window of opportunity. **Neurobiology of Disease**. https://doi.org/10.1016/j.nbd.2020.105173 📗

#. Vaysse, P-M. et al. (2020). Stromal vapors for real-time molecular guidance of breast-conserving surgery. **Scientific Reports**. https://doi.org/10.1038/s41598-020-77102-1 😞

#. Väyrynen, J. P. et al. (2020). Prognostic significance of immune cell populations identified by machine learning in colorectal cancer using routine hematoxylin & eosin stained sections, **Clinical Cancer Research**. http://doi.org/10.1158/1078-0432.CCR-20-0071 📗

#. Wahab, A. et al. (2020). Impact of Astroprincin (FAM171A1) Expression in Oral Tongue Cancer. **Frontiers in Oral Health**. https://doi.org/10.3389/froh.2020.599421 😞

#. Wakashin, H. et al. (2020). APOL1 renal risk variants exacerbate podocyte injury by increasing inflammatory stress. **BMC Nephrology**. https://doi.org/10.1186/s12882-020-01995-3 😞

#. Wang, A. et al. (2020). Treatment of granuloma annulare and suppression of proinflammatory cytokine activity with tofacitinib. **Journal of Allergy and Clinical Immunology**. https://doi.org/10.1016/j.jaci.2020.10.012 😞

#. Wheeler, D. A. et al. (2020). Molecular Features of Cancers Exhibiting Exceptional Responses to Treatment. **Cancer Cell**. https://doi.org/10.1016/j.ccell.2020.10.015 📗

#. Wirta, E-V. et al. (2020). Prognostic Value of Immune Environment Analysis in Small Bowel Adenocarcinomas with Verified Mutational Landscape and Predisposing Conditions. **Cancers**. https://doi.org/10.3390/cancers12082018 📗

#. Wood, A-C. et al. (2020). Deep Learning Predicts Molecular Subtype of Muscle-invasive Bladder Cancer from Conventional Histopathological Slides. **European Urology**. https://doi.org/10.1016/j.eururo.2020.04.023 📗

#. Wu, K. et al. (2020). Function-blocking RHAMM peptides attenuate fibrosis and promote anti-fibrotic adipokines in a bleomycin-induced murine model of systemic sclerosis. **Journal of Investigative Dermatology**. https://doi.org/10.1016/j.jid.2019.11.032 😞

#. Xie, C. et al. (2020). Immune checkpoint blockade in combination with stereotactic body radiotherapy in patients with metastatic pancreatic ductal adenocarcinoma. **Clinical Cancer Research**. https://doi.org/10.1158/1078-0432.CCR-19-3624 😞

#. Yang, T. et al. (2020). Small-molecule modulation of the p75 neurotrophin receptor inhibits a wide range of tau molecular pathologies and their sequelae in P301S tauopathy mice. **Acta Neuropathologica Communications**. https://doi.org/10.1186/s40478-020-01034-0 😞

#. Yatsenko, A. A. et al. (2020). Cultivation of Melanoma Cells in vitro on a 3D Scaffold Prepared on the Basis of Gelatin. **Cell and Tissue Biology**. https://doi.org/10.1134/S1990519X20060097 😞

#. Yildiz, S. et al. (2020). Respiratory tissue-associated commensal bacteria offer therapeutic potential against pneumococcal colonization. **eLife**. https://doi.org/10.7554/eLife.53581 😞

#. Yu, M. et al. (2020). Islet transplantation in the subcutaneous space achieves long-term euglycaemia in preclinical models of type 1 diabetes. **Nature Metabolism**. https://doi.org/10.1038/s42255-020-0269-7 📗

#. Zhang, G. et al. (2020). Based on Histogram Analysis: ADC<sub>aqp</sub> Derived from Ultra-high b-Value DWI could be a Non-invasive Specific Biomarker for Rectal Cancer Prognosis. **Scientific Reports**. https://doi.org/10.1038/s41598-020-67263-4 📗

#. Zhang, Y. et al. (2020). Mutant IDH Sensitizes Gliomas to Endoplasmic Reticulum Stress and Triggers Apoptosis via miR-183-Mediated Inhibition of Semaphorin 3E. **Cancer Research**. https://doi.org/10.1158/0008-5472.CAN-19-0054 📗

#. Zheng, H. et al. (2020). Overexpression of Long Noncoding RNA _HOTAIR_ Is a Unique Epigenetic Characteristic of Myxopapillary Ependymoma. **Journal of Neuropathology & Experimental Neurology**. https://doi.org/10.1093/jnen/nlaa103 📗

#. Zhou, S. et al. (2020). Deep learning assistance for the histopathologic diagnosis of *Helicobacter pylori*. **Intelligence-Based Medicine**. https://doi.org/10.1016/j.ibmed.2020.100004 📗

#. Zhu, L. et al. (2020). Focused ultrasound for safe and effective release of brain tumor biomarkers into the peripheral circulation. **PLOS ONE**. https://doi.org/10.1371/journal.pone.0234182 📗

#. de Jong, I. E. M. et al. (2020). Evidence for Recipient-Derived Cells in Peribiliary Glands and Biliary Epithelium of the Large Donor Bile Ducts After Liver Transplantation. **Frontiers in Cell and Developmental Biology**. https://doi.org/10.3389/fcell.2020.00693 📗

#. de Vries, G. et al. (2020). Establishment and characterisation of testicular cancer patient-derived xenograft models for preclinical evaluation of novel therapeutic strategies. **Scientific Reports**. https://doi.org/10.1038/s41598-020-75518-3 📗

#. de Winter, D. et al. (2020). Glomerular developmental delay and proteinuria in the preterm neonatal rabbit. **PLOS ONE**. https://doi.org/10.1371/journal.pone.0241384 📗

#. Śledzińska, A. et al. (2020). Regulatory T Cells Restrain Interleukin-2- and Blimp-1-Dependent Acquisition of Cytotoxic Function by CD4+ T Cells.  **Immunity**. https://doi.org/10.1016/j.immuni.2019.12.007 😞

#. Ščupáková, K. et al. (2020). Morphometric Cell Classification for Single‐Cell MALDI‐Mass Spectrometry Imaging. **Angewandte Chemie**. https://doi.org/10.1002/ange.202007315 📗
