2021 (243)
==========

#. Affo, S. et al. (2021). Promotion of cholangiocarcinoma growth by diverse cancer-associated fibroblast subpopulations. **Cancer Cell**. https://doi.org/10.1016/j.ccell.2021.03.012 📗

#. Ahtianinen, M. et al. (2021). Immune Contexture of MMR-Proficient Primary Colorectal Cancer and Matched Liver and Lung Metastases. **Cancers**. https://doi.org/10.3390/cancers13071530 📗

#. Al-Sahaf, S. et al. (2021). Increased Abundance of Tumour-Associated Neutrophils in HPV-Negative Compared to HPV-Positive Oropharyngeal Squamous Cell Carcinoma Is Mediated by IL-1R Signalling. **Frontiers in Oral Health**. https://doi.org/10.3389/froh.2021.604565 📗

#. Alame, M. et al. (2021). The immune contexture of primary central nervous system diffuse large B cell lymphoma associates with patient survival and specific cell signaling. **Theranostics**. https://dx.doi.org/10.7150%2Fthno.54343 📗

#. Alderdice, M. et al. (2021). Evolutionary genetic algorithm identifies _IL2RB_ as a potential predictive biomarker for immune-checkpoint therapy in colorectal cancer. **NAR Genomics and Bioinformatics**. https://doi.org/10.1093/nargab/lqab016 📗

#. Almeida, C. F. et al. (2021). Satellite cells deficiency and defective regeneration in dynamin 2‐related centronuclear myopathy. **The FASEB Journal**. https://doi.org/10.1096/fj.202001313RRR 📗

#. Alzghool, O. M. et al. (2021). (S)-[\ :sup:`18`\ F]THK5117 brain uptake is associated with Aβ plaques and MAO-B enzyme in a mouse model of Alzheimer’s disease. **Neuropharmacology**. https://doi.org/10.1016/j.neuropharm.2021.108676 📗

#. Amarilla, A. A. et al. (2021). A versatile reverse genetics platform for SARS-CoV-2 and other positive-strand RNA viruses. **Nature Communications**. https://doi.org/10.1038/s41467-021-23779-5 📗

#. Angelini, R. et al. (2021). Visualizing Cholesterol in the Brain by On-Tissue Derivatization and Quantitative Mass Spectrometry Imaging. **Analytical Chemistry**. https://dx.doi.org/10.1021/acs.analchem.0c05399 📗

#. Apaolaza, P. S. et al. (2021). Islet expression of type I interferon response sensors is associated with immune infiltration and viral infection in type 1 diabetes. **Science Advances**. https://doi.org/10.1126/sciadv.abd6527 📗

#. Aung, T. N. et al. (2021). A new tool for technical standardization of the Ki67 immunohistochemical assay. **Modern Pathology**. https://doi.org/10.1038/s41379-021-00745-6 📗

#. Avgustinova, A. et al. (2021). Repression of endogenous retroviruses prevents antiviral immune response and is required for mammary gland development. **Cell Stem Cell**. https://doi.org/10.1016/j.stem.2021.04.030 📗

#. Babak, M. V. et al. (2021). Interfering with metabolic profile of triple-negative breast cancers using rationally-designed metformin prodrugs. **Angewandte Chemie**. https://doi.org/10.1002/anie.202102266 😞

#. Bahmani, B. et al. (2021). Intratumoral immunotherapy using platelet-cloaked nanoparticles enhances antitumor immunity in solid tumors. **Nature Communications**. https://doi.org/10.1038/s41467-021-22311-z 😞

#. Baldavira, C. M. et al. (2021). The expression patterns and prognostic significance of pleckstrin homology-like domain family A (PHLDA) in lung cancer and malignant mesothelioma. **Journal of Thoracic Disease**. https://dx.doi.org/10.21037/jtd-20-2909 😞

#. Balkrishna, A. et al. (2021). Supercritical Fluid Extract of *Putranjiva roxburghii* Wall. Seeds Mitigates Fertility Impairment in a Zebrafish Model. **Molecules**. https://doi.org/10.3390/molecules26041020 📗

#. Baranova, K. et al. (2021). Evaluation of an open-source machine-learning tool to quantify bone marrow plasma cells. **Journal of Clinical Pathology**. http://dx.doi.org/10.1136/jclinpath-2021-207524 📗

#. Barber-Axthelm, I. M. et al. (2021). Stem cell–derived CAR T cells traffic to HIV reservoirs in macaques. **JCI Insight**. https://doi.org/10.1172/jci.insight.141502 📗

#. Bell, S. et al. (2021). Lesch-Nyhan disease causes impaired energy metabolism and reduced developmental potential in midbrain dopaminergic cells. **Stell Cell Reports**. https://doi.org/10.1016/j.stemcr.2021.06.003 😞

#. Belnoue, E. et al. (2021). Novel Protein-Based Vaccine against Self-Antigen Reduces the Formation of Sporadic Colon Adenomas in Mice. **Cancers**. https://doi.org/10.3390/cancers13040845 📗

#. Bhagavatula, S. et al. (2021). A Miniaturized Platform for Multiplexed Drug Response Imaging in Live Tumors. **Cancers**. https://doi.org/10.3390/cancers13040653 📗

#. Bleeser, T. et al. (2021). Effects of Maternal Abdominal Surgery on Fetal Brain Development in the Rabbit Model. **Fetal Diganosis and Therapy**. https://doi.org/10.1159/000512489 📗

#. Blocker, S. J. et al. (2021). Ex Vivo MR Histology and Cytometric Feature Mapping Connect Three-dimensional in Vivo MR Images to Two-dimensional Histopathologic Images of Murine Sarcomas. **Radiology: Imaging Cancer**. https://doi.org/10.1148/rycan.2021200103 📗

#. Boby, N. et al. (2021). Protective Effect of Pyrus ussuriensis Maxim. Extract against Ethanol-Induced Gastritis in Rats. **Antioxidants**. https://doi.org/10.3390/antiox10030439 😞

#. Bortolotti, D. et al. (2021). Late-onset intrauterine growth restriction and HHV-6 infection: A pilot study. **Journal of Medical Virology**. https://doi.org/10.1002/jmv.27138 😞

#. Boucher, Y. et al. (2021). Bevacizumab improves tumor infiltration of mature dendritic cells and effector T-cells in triple-negative breast cancer patients. **npj Precision Oncology**. https://doi.org/10.1038/s41698-021-00197-w 📗

#. Brait, V. H. et al. (2021). Longitudinal hippocampal volumetric changes in mice following brain infarction. **Scientific Reports**. https://doi.org/10.1038/s41598-021-88284-7 📗

#. Brinker, T. J. et al. (2021). Deep learning approach to predict sentinel lymph node status directly from routine histology of primary melanoma tumours. **European Journal of Cancer**. https://doi.org/10.1016/j.ejca.2021.05.026 📗

#. Brück, O. et al. (2021). Spatial immunoprofiling of the intratumoral and peritumoral tissue of renal cell carcinoma patients. **Modern Pathology**. https://doi.org/10.1038/s41379-021-00864-0 📗

#. Budczies, J. et al. (2021). Deciphering the immunosuppressive tumor microenvironment in ALK- and EGFR-positive lung adenocarcinoma. **Cancer Immunology, Immunotherapy** https://doi.org/10.1007/s00262-021-02981-w 😞

#. Buedts, L. et al. (2021). The landscape of copy number variations in classical Hodgkin lymphoma: a joint KU Leuven and LYSA study on cell-free DNA. **Blood Advances**. https://doi.org/10.1182/bloodadvances.2020003039 😞

#. Burgess, S. J. et al. (2021). The Role of Csmd1 during Mammary Gland Development. **Genes**. https://doi.org/10.3390/genes12020162 📗

#. Caldwell, C. et al. (2021). Validation of a DKK1 RNAscope chromogenic in situ hybridization assay for gastric and gastroesophageal junction adenocarcinoma tumors. **Scientific Reports**. https://doi.org/10.1038/s41598-021-89060-3 📗

#. Capitao, M. et al. (2021). Anti-Tumor Efficacy of PD-L1 Targeted Alpha-Particle Therapy in a Human Melanoma Xenograft Model. **Cancers**. https://doi.org/10.3390/cancers13061256 📗

#. Carstens, J. L. et al. (2021). Stabilized epithelial phenotype of cancer cells in primary tumors leads to increased colonization of liver metastasis in pancreatic cancer. **Cell Reports**. https://doi.org/10.1016/j.celrep.2021.108990 📗

#. Casanova-Acebes, M. et al. (2021). Tissue-resident macrophages provide a pro-tumorigenic niche to early NSCLC cells. **Nature**. https://doi.org/10.1038/s41586-021-03651-8 📗

#. Chen, C. et al. (2021). Imaging mass cytometry reveals generalised deficiency in OXPHOS complexes in Parkinson’s disease. **npj Parkinson's Disease**. https://doi.org/10.1038/s41531-021-00182-x 📗

#. Chen, K-T. et al. (2021). Neuronavigation-guided focused ultrasound for transcranial blood-brain barrier opening and immunostimulation in brain tumors. **Science Advances**. https://doi.org/10.1126/sciadv.abd0772 😞

#. Chodankar, R. R. et al. (2021). The endometrial response to modulation of ligand-progesterone receptor pathways is reversible. **Fertility and Sterility**. https://doi.org/10.1016/j.fertnstert.2021.02.008 📗

#. Cieśla, M. et al. (2021). Oncogenic translation directs spliceosome dynamics revealing an integral role for SF3A3 in breast cancer. **Molecular Cell**. https://doi.org/10.1016/j.molcel.2021.01.034 📗

#. Ciregia, F. et al. (2021). Modulation of αVβ6 integrin in osteoarthritis-related synovitis and the interaction with VTN<sub>(381–397 a.a.)</sub> competing for TGF-β1 activation. **Experimental & Molecular Medicine**. https://doi.org/10.1038/s12276-021-00558-2 📗

#. Cizkova, K. et al. (2021). Comparative Analysis of Immunohistochemical Staining Intensity Determined by Light Microscopy, ImageJ and QuPath in Placental Hofbauer Cells. **Acta Histochemica et Cytochemica**. https://doi.org/10.1267/ahc.20-00032 📗

#. Consonni, F. M. et al. (2021). Heme catabolism by tumor-associated macrophages controls metastasis formation. **Nature Immunology**. https://doi.org/10.1038/s41590-021-00921-5 😞

#. Dabagian, H. et al. (2021). PARP Targeted Alpha-Particle Therapy Enhances Response to PD-1 Immune-Checkpoint Blockade in a Syngeneic Mouse Model of Glioblastoma. **ACS Pharmacology & Translational Science**. https://doi.org/10.1021/acsptsci.0c00206 😞

#. Dahabieh, M. S. et al. (2021). Silencing PEX26 as an Unconventional Mode to Kill Drug-Resistant Cancer Cells and Forestall Drug Resistance. **Autophagy**. https://doi.org/10.1080/15548627.2021.1936932 😞

#. De Andrea, C. E. et al. (2021). Heterogenous presence of Neutrophil Extracellular Traps in human solid tumours is partially dependent on Interleukin-8. **Journal of Pathology**. https://doi.org/10.1002/path.5753 😞

#. De Angelis, P. M. (2021). DNA Repair Protein Expression and Oxidative/Nitrosative Stress in Ulcerative Colitis and Sporadic Colorectal Cancer. **Anticancer Research**. https://doi.org/10.21873/anticanres.15112 📗

#. Delanghe, T. et al. (2021). Antioxidant and food additive BHA prevents TNF cytotoxicity by acting as a direct RIPK1 inhibitor. **Cell Death & Disease**. https://doi.org/10.1038/s41419-021-03994-0 😞

#. Ding, J. J. et al. (2021). Vagus nerve stimulation does not alter brainstem nuclei morphology in patients with refractory epilepsy. **Epilepsy & Behavior**. https://doi.org/10.1016/j.yebeh.2021.107940 📗

#. Dittmayer, C. et al. (2021). Preparation of Samples for Large-Scale Automated Electron Microscopy of Tissue and Cell Ultrastructure. **Microscopy and Microanalysis**. https://doi.org/10.1017/S1431927621011958 📗

#. Duan, K. et al. (2021). The value of GATA6 immunohistochemistry and computer-assisted diagnosis to predict clinical outcome in advanced pancreatic cancer. **Scientific Reports**. https://doi.org/10.1038/s41598-021-94544-3 📗

#. Duran, J. et al. (2021). Astrocytic glycogen accumulation drives the pathophysiology of neurodegeneration in Lafora disease. **Brain**. https://doi.org/10.1093/brain/awab110 📗

#. Ember, K. J. I. et al. (2021). Non‐invasive detection of ischemic vascular damage in a pig model of liver donation after circulatory death. **Hepatology**. https://doi.org/10.1002/hep.31701 📗

#. Ercolano, G. et al. (2021). PPARɣ drives IL-33-dependent ILC2 pro-tumoral functions. **Nature Communications**. https://doi.org/10.1038/s41467-021-22764-2 📗

#. Esmail, S. et al. (2021). Rapid and accurate agglutination-based testing for SARS-CoV-2 antibodies. **Cell Reports Methods**. https://doi.org/10.1016/j.crmeth.2021.100011 😞

#. Eustace, A. J. et al. (2021). The role of infiltrating lymphocytes in the neo-adjuvant treatment of women with HER2-positive breast cancer. **Breast Cancer Research and Treatment**. https://doi.org/10.1007/s10549-021-06244-1 📗

#. Favre, L. et al. (2021). Idylla MSI test as a new tool for microsatellite instability detection in sebaceous tumours and keratoacanthomas. **Journal of Clinical Pathology**. http://dx.doi.org/10.1136/jclinpath-2021-207606 😞

#. Fetz, A. et al. (2021). Spray coagulation with snare-tip versus argon plasma coagulation: An ex vivo study evaluating tissue effects. **Endoscopy International Open**. https://doi.org/10.1055/a-1373-4162 😞

#. Fischietti, M. et al. (2021). Schlafen 5 as a novel therapeutic target in pancreatic ductal adenocarcinoma. **Oncogene**. https://doi.org/10.1038/s41388-021-01761-1 😞

#. Foersch, S. et al. (2021). Deep learning for diagnosis and survival prediction in soft tissue sarcoma. **Annals of Oncology**. https://doi.org/10.1016/j.annonc.2021.06.007 📗

#. Friedrich, M. et al. (2021). Intrathecal activation of CD8\ :sup:`+` memory T cells in IgG4-related disease of the brain parenchyma. **EMBO Molecular Medicine**. https://doi.org/10.15252/emmm.202113953 😞

#. Fujii, T. et al. (2021). MEF2C regulates osteoclastogenesis and pathologic bone resorption via c-FOS. **Bone Research**. https://doi.org/10.1038/s41413-020-00120-2 😞

#. Ganig, N. et al. (2021). Proteomic Analyses of Fibroblast- and Serum-Derived Exosomes Identify QSOX1 as a Marker for Non-invasive Detection of Colorectal Cancer. **Cancers**. https://doi.org/10.3390/cancers13061351 📗

#. Garcia, D. I. et al. (2021). High-Fat Diet Drives an Aggressive Pancreatic Cancer Phenotype. **Journal of Surgical Research**. https://doi.org/10.1016/j.jss.2020.10.007 😞

#. Garcia-Mesa, Y. et al. (2021). Dimethyl Fumarate, an Approved Multiple Sclerosis Treatment, Reduces Brain Oxidative Stress in SIV-Infected Rhesus Macaques: Potential Therapeutic Repurposing for HIV Neuroprotection. **Antioxidants**. https://doi.org/10.3390/antiox10030416 😞

#. Ge, P. et al. (2021). M. tuberculosis PknG manipulates host autophagy flux to promote pathogen intracellular survival. **Augophagy**. https://doi.org/10.1080/15548627.2021.1938912 😞

#. Go, D.-M. et al. (2021). Programmed Death Ligand 1-Expressing Classical Dendritic Cells Mitigate *Helicobacter*-Induced Gastritis. **Cellular and Molecular Gastroenterology and Hepatology**. https://doi.org/10.1016/j.jcmgh.2021.04.007 😞

#. Go, D.-M. et al. (2021). Regulation of Helicobacter-induced gastritis by programmed death ligand 1- expressing classical dendritic cells. **Cellular and Molecular Gastroenterology and Hepatology**. https://doi.org/10.1016/j.jcmgh.2021.04.007 😞

#. Gong, Y. et al. (2021). Age-Associated Proteomic Signatures and Potential Clinically Actionable Targets of Colorectal Cancer. **Molecular & Cellular Proteomics**.  https://doi.org/10.1016/j.mcpro.2021.100115 😞

#. Goubet, A.-G. et al. (2021). Multifaceted modes of action of the anticancer probiotic *Enterococcus hirae*. **Cell Death & Differentiation**. https://doi.org/10.1038/s41418-021-00753-8 📗

#. Govaerts, I. et al. (2021). PSEN1-selective gamma-secretase inhibition in combination with kinase or XPO-1 inhibitors effectively targets T cell acute lymphoblastic leukemia. **Journal of Hematology & Oncology**. https://doi.org/10.1186/s13045-021-01114-1 😞

#. Grisaru-Tal, S. et al. (2021). Primary tumors from mucosal barrier organs drive unique eosinophil infiltration patterns and clinical associations. **OncoImmunology**. https://doi.org/10.1080/2162402X.2020.1859732 📗

#. Gudiño, V. et al. (2021). RAC1B modulates intestinal tumourigenesis via modulation of WNT and EGFR signalling pathways. **Nature Communications**. https://doi.org/10.1038/s41467-021-22531-3 😞

#. Han, Y. N. et al. (2021). Nitric Oxide Produced by the Antioxidant Activity of Verapamil Improves the Acute Wound Healing Process. **Tissue Engineering and Regenerative Medicine**. https://doi.org/10.1007/s13770-020-00308-x 😞

#. Harms, K. et al. (2021). Virus-positive Merkel cell carcinoma is an independent prognostic group with distinct predictive biomarkers. **Clinical Cancer Research**. https://doi.org/10.1158/1078-0432.CCR-20-0864 😞

#. Hartmann, O. et al. (2021). Implementation of CRISPR/Cas9 Genome Editing to Generate Murine Lung Cancer Models That Depict the Mutational Landscape of Human Disease. **Frontiers in Cell and Developmental Biology**. https://doi.org/10.3389/fcell.2021.641618 😞

#. Hasan, N. et al. (2021). Brown adipocyte-specific knockout of Bmal1 causes mild but significant impairment of thermogenesis in mice. **Molecular Metabolism**. https://doi.org/10.1016/j.molmet.2021.101202 📗

#. Heij, L. R. et al. (2021). Nerve Fibers in the Tumor Microenvironment Are Co-Localized with Lymphoid Aggregates in Pancreatic Cancer. **Journal of Clinical Medicine**. https://doi.org/10.3390/jcm10030490 😞

#. Heusler, I. et al. (2021). Enhanced expression of Galectin-3 in Gestational Diabetes. **Nutrition, Metabolism and Cardiovascular Diseases**. https://doi.org/10.1016/j.numecd.2021.03.002 📗

#. Hiltunen, N. et al. (2021). CD3+, CD8+, CD4+ and FOXP3+ T Cells in the Immune Microenvironment of Small Bowel Neuroendocrine Tumors. **Diseases**. https://doi.org/10.3390/diseases9020042 📗

#. Hiss, S. et al. (2021). Tumour-Infiltrating Lymphocytes (TILs) and PD-L1 Expression Correlate with Lymph Node Metastasis, High-Grade Transformation and Shorter Metastasis-Free Survival in Patients with Acinic Cell Carcinoma (AciCC) of the Salivary Glands. **Cancers**. https://doi.org/10.3390/cancers13050965 😞

#. Holanek, M. et al. (2021). Neoadjuvant Chemotherapy of Triple-Negative Breast Cancer: Evaluation of Early Clinical Response, Pathological Complete Response Rates, and Addition of Platinum Salts Benefit Based on Real-World Evidence. **Cancers**. https://doi.org/10.3390/cancers13071586 📗

#. Hollingshead, B. D. et al. (2021). An Orthogonal Methods Assessment of Topical Drug Concentrations in Skin and the Impact for Risk Assessment in the Viable Epidermis. **Regulatory Toxicology and Pharmacology**. https://doi.org/10.1016/j.yrtph.2021.104934 📗

#. Holzgreve, A. et al. (2021). PSMA Expression in Glioblastoma as a Basis for Theranostic Approaches: A Retrospective, Correlational Panel Study Including Immunohistochemistry, Clinical Parameters and PET Imaging. **Frontiers in Oncology**. https://doi.org/10.3389/fonc.2021.646387 📗

#. Hong, L. et al. (2021). Multi-omics reveals a relationship between endometrial amino acid metabolism and autophagy in women with recurrent miscarriage. **Biology of Reproduction**. https://doi.org/10.1093/biolre/ioab101 😞

#. Howard, F. M. et al. (2021). The impact of site-specific digital histology signatures on deep learning model accuracy and bias. **Nature Communications**. https://doi.org/10.1038/s41467-021-24698-1 😞

#. Hu, Z. et al. (2021). The Oxford Classic Links Epithelial-to-Mesenchymal Transition to Immunosuppression in Poor Prognosis Ovarian Cancers. **Clinical Cancer Research**. https://doi.org/10.1158/1078-0432.CCR-20-2782 📗

#. Huang, T.-W. et al. (2021). Glial-Specific Deletion of Med12 Results in Rapid Hearing Loss via Degradation of the Stria Vascularis. **Journal of Neuroscience**. https://doi.org/10.1523/JNEUROSCI.0070-21.2021 📗

#. Hubert, P. et al. (2021). Extracellular HMGB1 blockade inhibits tumor growth through profoundly remodeling immune microenvironment and enhances checkpoint inhibitor-based immunotherapy. **Journal for ImmunoTherapy of Cancer**. http://dx.doi.org/10.1136/jitc-2020-001966 📗

#. Huhtakangas, J. A. et al. (2021). A single intra-articular dose of vitamin D analog calcipotriol alleviates synovitis without adverse effects in rats. **PLOS ONE**. https://doi.org/10.1371/journal.pone.0250352 📗

#. Hwang, J-H. et al. (2021). Ex Vivo Live Full-Thickness Porcine Skin Model as a Versatile In Vitro Testing Method for Skin Barrier Research. **International Journal of Molecular Sciences**. https://doi.org/10.3390/ijms22020657 📗

#. Höhn, J. et al. (2021). Combining CNN-based histologic whole slide image analysis and patient data to improve skin cancer classification. **European Journal of Cancer**. https://doi.org/10.1016/j.ejca.2021.02.032 📗

#. Jacobs, S. M. et al. (2021). CXCR4 expression in glioblastoma tissue and the potential for PET imaging and treatment with [68Ga]Ga-Pentixafor /[177Lu]Lu-Pentixather. **European Journal of Nuclear Medicine and Molecular Imaging**. https://doi.org/10.1007/s00259-021-05196-4 📗

#. Jacquelot, N. et al. (2021). Blockade of the co-inhibitory molecule PD-1 unleashes ILC2-dependent antitumor immunity in melanoma. **Nature Immunology**. https://doi.org/10.1038/s41590-021-00943-z 📗

#. Janic, B. et al. (2021). Therapeutic enhancement of radiation and immunomodulation by gold nanoparticles in triple negative breast cancer. **Cancer Biology & Therapy**. https://doi.org/10.1080/15384047.2020.1861923 📗

#. Junttila, A. et al. (2021). Immune cell score, PD-L1 expression and prognosis in esophageal cancer. **Acta Oncologica**. https://doi.org/10.1080/0284186X.2020.1868571 📗

#. Kallionpää, R. A. et al. (2021). Mast Cells in Human Cutaneous Neurofibromas: Density, Subtypes, and Association with Clinical Features in Neurofibromatosis 1. **Dermatology**. https://doi.org/10.1159/000517011 📗

#. Karnell, J. L. et al. (2021). Depleting plasmacytoid dendritic cells reduces local type I interferon responses and disease activity in patients with cutaneous lupus. **Science Translational Medicine**. https://doi.org/10.1126/scitranslmed.abf8442 😞

#. Kaufmann, J. et al. (2021). Using the R Package Spatstat to Assess Inhibitory Effects of Microregional Hypoxia on the Infiltration of Cancers of the Head and Neck Region by Cytotoxic T Lymphocytes. **Cancers**. https://doi.org/10.3390/cancers13081924 📗

#. Kay, J. E. et al. (2021). Excision of mutagenic replication-blocking lesions suppresses cancer but promotes cytotoxicity and lethality in nitrosamine-exposed mice. **Cell Reports**. https://doi.org/10.1016/j.celrep.2021.108864 📗

#. Kazdal, D. et al. (2021). Conventional and semi-automatic histopathological analysis of tumor cell content for multigene sequencing of lung adenocarcinoma. **Translational Lung Cancer Research**. https://doi.org/10.21037/tlcr-20-1168 📗

#. Kerselidou, D. et al. (2021). Alternative glycosylation controls endoplasmic reticulum dynamics and tubular extension in mammalian cells. **Science Advances**. https://doi.org/10.1126/sciadv.abe8349 😞

#. Kim, B. et al. (2021). Tau immunotherapy is associated with glial responses in FTLD-tau. **Acta Neuropathologica**. https://doi.org/10.1007/s00401-021-02318-y 📗

#. Kotlov, N. et al. (2021). Clinical and biological subtypes of B-cell lymphoma revealed by microenvironmental signatures. **Cancer Discovery**. https://doi.org/10.1158/2159-8290.CD-20-0839 📗

#. Kurnit, K. C. et al. (2021). Loss of CD73 shifts transforming growth factor-β1 (TGF-β1) from tumor suppressor to promoter in endometrial cancer. **Cancer Letters**. https://doi.org/10.1016/j.canlet.2021.01.030 📗

#. Kuyl, E.-V. et al. (2021). Inhibition of PAD4 mediated neutrophil extracellular traps prevents fibrotic osseointegration failure in a tibial implant murine model. **The Bone & Joint Journal**. https://doi.org/10.1302/0301-620X.103B7.BJJ-2020-2483.R1 📗

#. Kvietkauskas, M. et al. (2021). Dietary Melatonin and Glycine Decrease Tumor Growth through Antiangiogenic Activity in Experimental Colorectal Liver Metastasis. **Nutrients**. https://doi.org/10.3390/nu13062035 📗

#. Kwon, H.-H. et al. (2021). Dual therapeutic targeting of intra-articular inflammation and intracellular bacteria enhances chondroprotection in septic arthritis. **Science Advances**. https://doi.org/10.1126/sciadv.abf2665 📗

#. Kwon, J-T. et al. (2021). An amygdala circuit that suppresses social engagement. **Nature**. https://doi.org/10.1038/s41586-021-03413-6 📗

#. Labadie, K. P. et al. (2021). Glypican-3 targeted delivery of :sup:`89`\ Zr and :sup:`90`\ Y as a theranostic radionuclide platform for hepatocellular carcinoma. **Scientific Reports**. https://doi.org/10.1038/s41598-021-82172-w 😞

#. Lamont, L. et al. (2021). Quantitative mass spectrometry imaging of drugs and metabolites: a multiplatform comparison. **Analytical and Bioanalytical Chemistry**. https://doi.org/10.1007/s00216-021-03210-0 😞

#. Lau, C. et al. (2021). The Voronoi theory of the normal liver lobular architecture and its applicability in hepatic zonation. **Scientific Reports**. https://doi.org/10.1038/s41598-021-88699-2 😞

#. Lee, J. E. et al. (2021). Olig2 regulates p53-mediated apoptosis, migration and invasion of melanoma cells. **Scientific Reports**. https://doi.org/10.1038/s41598-021-87438-x 😞

#. Lee, M. Y. et al. (2021). Chimeric antigen receptor engineered NK cellular immunotherapy overcomes the selection of T-cell escape variant cancer cells. **Journal for ImmunoTherapy of Cancer**. http://dx.doi.org/10.1136/jitc-2020-002128 📗

#. Lee, M. Y. et al. (2021). Preclinical study of a novel therapeutic vaccine for recurrent respiratory papillomatosis. **npj Vaccines**. https://doi.org/10.1038/s41541-021-00348-x 📗

#. Levitin, F. et al. (2021). Oxygen-independent disulfide bond formation in VEGF-A and CA9. **Journal of Biological Chemistry**. https://doi.org/10.1016/j.jbc.2021.100505 📗

#. Li, T. et al. (2021). Endometrial laminin subunit beta-3 expression associates with reproductive outcome in patients with repeated implantation failure. **Journal of Assisted Reproduction and Genetics**. https://doi.org/10.1007/s10815-021-02135-y 📗

#. Lin, T.-Y. et al. (2021). Fibroblast dedifferentiation as a determinant of successful regeneration. **Developmental Cell**. https://doi.org/10.1016/j.devcel.2021.04.016 📗

#. Lindquist, K. E. et al. (2021). Difficulties in diagnostics of lung tumours in biopsies: an interpathologist concordance study evaluating the international diagnostic guidelines. **Journal of Clinical Pathology**. http://dx.doi.org/10.1136/jclinpath-2020-207257 😞

#. Liu, X. et al. (2021). Modelling human blastocysts by reprogramming fibroblasts into iBlastoids. **Nature**. https://doi.org/10.1038/s41586-021-03372-y 📗

#. Low, J.-L. et al. (2021). Molecular docking-aided identification of small molecule inhibitors targeting b-catenin-TCF4 interaction. **iScience**. https://doi.org/10.1016/j.isci.2021.102544 📗

#. Lu, Y.-A. et al. (2021). Single-Nucleus RNA Sequencing Identifies New Classes of Proximal Tubular Epithelial Cells in Kidney Fibrosis. **Journal of the American Society of Nephrology**. https://doi-org.ezproxy.is.ed.ac.uk/10.1681/ASN.2020081143 📗

#. Luchicchi, A. et al. (2021). Axon‐myelin unit blistering as early event in MS normal appearing white matter. **Annals of Neurology**. https://doi.org/10.1002/ana.26014 😞

#. Luo, X. et al. (2021). IL-23/IL-17A/TRPV1 axis produces mechanical pain via macrophage-sensory neuron crosstalk in female mice. **Neuron**. https://doi.org/10.1016/j.neuron.2021.06.015 😞

#. López-Martínez, S. et al. (2021). A Natural Xenogeneic Endometrial Extracellular Matrix Hydrogel Toward Improving Current Human *in vitro* Models and Future *in vivo* Applications. **Frontiers in Bioengineering and Biotechnology**. https://doi.org/10.3389/fbioe.2021.639688 📗

#. Ma, L. et al. (2021). Epithelial-to-mesenchymal transition contributes to the downregulation of progesterone receptor expression in endometriosis lesions. **The Journal of Steroid Biochemistry and Molecular Biology**. https://doi.org/10.1016/j.jsbmb.2021.105943 😞

#. Mahbod, A. et al. (2021). CryoNuSeg: A dataset for nuclei instance segmentation of cryosectioned H&E-stained histological images. **Computers in Biology and Medicine**. https://doi.org/10.1016/j.compbiomed.2021.104349 😞

#. Martin, L. et al. (2021). Induction of contralateral hepatic hypertrophy by unilobar 90Y transarterial radioembolization vs. portal vein embolization: an animal study. **Journal of Vascular and Interventional Radiology**. https://doi.org/10.1016/j.jvir.2021.01.281 😞

#. Martin, S. K. et al. (2021). Disruption of DNA polymerase ζ engages an innate immune response. **Cell Reports**. https://doi.org/10.1016/j.celrep.2021.108775 😞

#. Matikas, A. et al. (2021). Prognostic role of serum thymidine kinase 1 kinetics during neoadjuvant chemotherapy for early breast cancer. **ESMO Open**. https://doi.org/10.1016/j.esmoop.2021.100076 📗

#. McElvain, L. E. et al. (2021). Specific populations of basal ganglia output neurons target distinct brain stem areas while collateralizing throughout the diencephalon. **Neurone**. https://doi.org/10.1016/j.neuron.2021.03.017 📗

#. Meeusen, B. et al. (2021). *PPP2R4* dysfunction promotes *KRAS*-mutant lung adenocarcinoma development and mediates opposite responses to MEK and mTOR inhibition. **Cancer Letters**. https://doi.org/10.1016/j.canlet.2021.06.022 📗

#. Mihola, O. et al. (2021). Rat PRDM9 shapes recombination landscapes, duration of meiosis, gametogenesis, and age of fertility. **BMC Biology**. https://doi.org/10.1186/s12915-021-01017-0 📗

#. Mirra, S. et al. (2021). ARMCX3 Mediates Susceptibility to Hepatic Tumorigenesis Promoted by Dietary Lipotoxicity. **Cancers**. https://doi.org/10.3390/cancers13051110 😞

#. Mitchell, J. L. et al. (2021). Histological and immunohistochemical features suggesting aetiological differences in lymph node and (muco) cutaneous feline tuberculosis lesions. **Journal of Small Animal Practice**. https://doi.org/10.1111/jsap.13386 📗

#. Mo, Y.-Q. et al. (2021). Ultrasonography predicts the results of labial salivary gland biopsy in patients with suspected Sjögren’s syndrome: a matrix risk model. **Therapeutic Advances in Musculoskeletal Disease**. https://doi.org/10.1177/1759720X211010592 😞

#. Monserrat, J. et al. (2021). Disruption of the MSL complex inhibits tumour maintenance by exacerbating chromosomal instability. **Nature Cell Biology**. https://doi.org/10.1038/s41556-021-00657-2 😞

#. Moon, C. S. et al. (2021). *FYN–TRAF3IP2* induces NF-κB signaling-driven peripheral T-cell lymphoma. **Nature Cancer**. https://doi.org/10.1038/s43018-020-00161-w 😞

#. Moore, M. R. et al. (2021). Automated digital TIL analysis (ADTA) adds prognostic value to standard assessment of depth and ulceration in primary melanoma. **Scientific Reports**. https://doi.org/10.1038/s41598-021-82305-1 📗

#. Morabito, S. et al. (2021). Single-nucleus chromatin accessibility and transcriptomic characterization of Alzheimer’s disease. **Nature Genetics**. https://doi.org/10.1038/s41588-021-00894-z 😞

#. Mori, H. et al. (2021). Characterizing the Tumor Immune Microenvironment with Tyramide-Based Multiplex Immunofluorescence. **Journal of Mammary Gland Biology and Neoplasia**. https://doi.org/10.1007/s10911-021-09479-2 📗

#. Moulee, D. A. et al. (2021). Classifying Retinal Degeneration in Histological Sections Using Deep Learning. **Translational Vision Science & Technology**. https://doi.org/10.1167/tvst.10.7.9 📗

#. Muiño, E. et al. (2021). Genome-wide transcriptome study in skin biopsies reveals an association of _E2F4_ with cadasil and cognitive impairment. **Scientific Reports**. https://doi.org/10.1038/s41598-021-86349-1 📗

#. Mulholland, M. et al. (2021). IL-2Rβγ signalling in lymphocytes promotes systemic inflammation and reduces plasma cholesterol in atherosclerotic mice. **Atherosclerosis**. https://doi.org/10.1016/j.atherosclerosis.2021.04.010 📗

#. Mullen, P. J. et al. (2021). SARS-CoV-2 infection rewires host cell metabolism and is potentially susceptible to mTORC1 inhibition. **Nature Communications**. https://doi.org/10.1038/s41467-021-22166-4 😞

#. Muñoz, N. M. et al. (2021). Influence of injection technique, drug formulation and tumor microenvironment on intratumoral immunotherapy delivery and efficacy. **Journal for ImmunoTherapy of Cancer**. http://dx.doi.org/10.1136/jitc-2020-001800 📗

#. Mylonas, K. J. et al. (2021). Cellular senescence inhibits renal regeneration after injury in mice, with senolytic treatment promoting repair. **Science Translational Medicine**. https://doi.org/10.1126/scitranslmed.abb0203 📗

#. Mäkinen, A. et al. (2021). _IGF2BP3_ Associates with Proliferative Phenotype and Prognostic Features in B-Cell Acute Lymphoblastic Leukemia. **Cancers**. https://doi.org/10.3390/cancers13071505 📗

#. Mäkinen, E. et al. (2021). Rats bred for low intrinsic aerobic exercise capacity link obesity with brain inflammation and reduced structural plasticity of the hippocampus. **Brain, Behavior, and Immunity**. https://doi.org/10.1016/j.bbi.2021.06.017 📗

#. Neumann, J. M. et al. (2021). A new technological approach in diagnostic pathology: mass spectrometry imaging-based metabolomics for biomarker detection in urachal cancer. **Laboratory Investigation**. https://doi.org/10.1038/s41374-021-00612-7 📗

#. Nguyen, T. T. et al. (2021). The impact of locally-delivered tacrolimus-releasing microspheres and polyethylene glycol-based islet surface modification on xenogeneic islet survival. **Journal of Controlled Release**. https://doi.org/10.1016/j.jconrel.2021.06.020 😞

#. Ni, H. et al. (2021). SATB2 defect promotes colitis and colitis-associated colorectal cancer by impairing Cl- /HCO3- exchange and homeostasis of gut microbiota. **Journal of Crohn's and Colitis**. https://doi.org/10.1093/ecco-jcc/jjab094 📗

#. Niogret, J. et al. (2021). Follicular helper-T cells restore CD8+-dependent antitumor immunity and anti-PD-L1/PD-1 efficacy. **Journal for ImmunoTherapy of Cancer**. http://dx.doi.org/10.1136/jitc-2020-002157 📗

#. Nolan, G. S. et al. (2021). Histological analysis of fat grafting with platelet-rich plasma for diabetic foot ulcers—A randomised controlled trial. **International Wound Journal**. https://doi.org/10.1111/iwj.13640 📗

#. Nortunen, M. et al. (2021). Pathophysiology of reflux oesophagitis: role of Toll-like receptors 2 and 4 and Farnesoid X receptor. **Virchows Archiv**. https://doi.org/10.1007/s00428-021-03066-w 📗

#. Novelli, G. et al. (2021). Inhibition of HECT E3 ligases as potential therapy for COVID-19. **Cell Death & Disease**. https://doi.org/10.1038/s41419-021-03513-1 😞

#. O'Grady, N. et al. (2021). PRoBE the cloud toolkit: finding the best biomarkers of drug response within a breast cancer clinical trial. **JAMIA Open**. https://doi.org/10.1093/jamiaopen/ooab038 📗

#. Oh, K. S. et al. (2021). Cellular senescence evaluated by P16INK4a immunohistochemistry is a prevalent phenomenon in advanced calcific aortic valve disease. **Cardiovascular Pathology**. https://doi.org/10.1016/j.carpath.2021.107318 📗

#. Olpe, C. et al. (2021). A diffusion-like process accommodates new crypts during clonal expansion in human colonic epithelium. **Gastroenterology**. https://doi.org/10.1053/j.gastro.2021.04.035 📗

#. Paik, S. et al. (2021). Systematic evaluation of scoring methods for Ki67 as a surrogate for 21-gene recurrence score. **npj Breast Cancer**. https://doi.org/10.1038/s41523-021-00221-z 📗

#. Paradis, J. S. et al. (2021). Synthetic Lethal Screens Reveal Co-Targeting FAK and MEK as a Multimodal Precision Therapy for GNAQ-Driven Uveal Melanoma. **Clinical Cancer Research**. https://doi.org/10.1158/1078-0432.CCR-20-3363 📗

#. Parkes, E. E. et al. (2021). The clinical and molecular significance associated with STING signaling in breast cancer. **npj Breast Cancer**. https://doi.org/10.1038/s41523-021-00283-z 📗

#. Pei, J. et al. (2021). Multi-omics integration identifies key upstream regulators of pathomechanisms in hypertrophic cardiomyopathy due to truncating MYBPC3 mutations. **Clinical Epigenetics**. https://doi.org/10.1186/s13148-021-01043-3 😞

#. Peixoto-Santos, J. E. et al. (2021). Neuropathology of the 21th century for the Latin American epilepsy community. **Seizure**. https://doi.org/10.1016/j.seizure.2021.02.003 📗

#. Pennanen, P. et al. (2021). Signaling pathways in human osteoclasts differentiation: ERK1/2 as a key player. **Molecular Biology Reports**. https://doi.org/10.1007/s11033-020-06128-5 📗

#. Petruk, N. et al. (2021). CD73 facilitates EMT progression and promotes lung metastases in triple-negative breast cancer. **Scientific Reports**. https://doi.org/10.1038/s41598-021-85379-z 📗

#. Picon, C. et al. (2021). Neuron-specific activation of necroptosis signaling in multiple sclerosis cortical grey matter. **Acta Neuropathologica**. https://doi.org/10.1007/s00401-021-02274-7 😞

#. Quaas, A. et al. (2021). Sex-specific prognostic effect of CD66b-positive tumor-infiltrating neutrophils (TANs) in gastric and esophageal adenocarcinoma. **Gastric Cancer**. https://doi.org/10.1007/s10120-021-01197-2 📗

#. Rakaee, M. et al. (2021). Tertiary lymphoid structure score: a promising approach to refine the TNM staging in resected non-small cell lung cancer. **British Journal of Cancer**. https://doi.org/10.1038/s41416-021-01307-y 😞

#. Ray, R. M. et al. (2021). Enhanced target cell specificity and uptake of lipid nanoparticles using RNA aptamers and peptides. **Beilstein Journal of Organic Chemistry**. https://doi.org/10.3762/bjoc.17.75 📗

#. Reischl, S. et al. (2021). Ac2-26-Nanoparticles Induce Resolution of Intestinal Inflammation and Anastomotic Healing via Inhibition of NF-κB Signaling in a Model of Perioperative Colitis. **Inflammatory Bowel Diseases**. https://doi.org/10.1093/ibd/izab008 📗

#. Riese, J. et al. (2021). Sphingosine-1-Phosphate Receptor Type 4 (S1P4) Is Differentially Regulated in Peritoneal B1 B Cells upon TLR4 Stimulation and Facilitates the Egress of Peritoneal B1a B Cells and Subsequent Accumulation of Splenic IRA B Cells under Inflammatory Conditions. **International Journal of Molecular Sciences**. https://doi.org/10.3390/ijms22073465 📗

#. Rogers, R. G. et al. (2021). Cardiosphere-derived cells, with and without a biological scaffold, stimulate myogenesis and recovery of muscle function in mice with volumetric muscle loss. **Biomaterials**. https://doi.org/10.1016/j.biomaterials.2021.120852 😞

#. Rubio, T. et al. (2021). The phosphatase PRL-3 affects intestinal homeostasis by altering the crypt cell composition. **Journal of Molecular Medicine**. https://doi.org/10.1007/s00109-021-02097-9 😞

#. Ruiz, E. J. et al. (2021). JunD, not c-Jun, is the AP-1 transcription factor required for Ras-induced lung cancer. **JCI Insight**. https://doi.org/10.1172/jci.insight.124985 📗

#. Sadras, T. et al. (2021). Developmental partitioning of SYK and ZAP70 prevents autoimmunity and cancer. **Molecular Cell**. https://doi.org/10.1016/j.molcel.2021.03.043 📗

#. Saghafinia, S. et al. (2021). Cancer cells retrace a stepwise differentiation program during malignant progression. **Cancer Discovery**. https://doi.org/10.1158/2159-8290.CD-20-1637 📗

#. Sajiki, Y. et al. (2021). Tick saliva-induced programmed death-1 and PD-ligand 1 and its related host immunosuppression. **Scientific Reports**. https://doi.org/10.1038/s41598-020-80251-y 😞

#. Salmi, L. et al. (2021). Growth Arrest-Specific Gene 6 Administration Ameliorates Sepsis-Induced Organ Damage in Mice and Reduces ROS Formation In Vitro. **Cells**. https://doi.org/10.3390/cells10030602 😞

#. Samain, R. et al. (2021). Pharmacological normalization of pancreatic cancer-associated fibroblast secretome impairs pro-metastatic cross-talk with macrophages. **Cellular and Molecular Gastroenterology and Hepatology**. https://doi.org/10.1016/j.jcmgh.2021.01.008 😞

#. Scholz, O. et al. (2021). Peripherally active dextromethorphan derivatives lower blood glucose levels by targeting pancreatic islets. **Cell Chemical Biology**. https://doi.org/10.1016/j.chembiol.2021.05.011 📗

#. Schupp, J. et al. (2021). In-Depth Immune-Oncology Studies of the Tumor Microenvironment in a Humanized Melanoma Mouse Model. **International Journal of Molecular Sciences**. https://doi.org/10.3390/ijms22031011 📗

#. Selven, H. et al. (2021). High expression of microRNA-126 relates to favorable prognosis for colon cancer patients. **Scientific Reports**. https://doi.org/10.1038/s41598-021-87985-3 📗

#. Seok, J. Y. et al. (2021). Diagnostic Utility of INSM1 in Medullary Thyroid Carcinoma. **International Journal of Surgical Pathology**. https://doi.org/10.1177/1066896921995935 📗

#. Shamseddin, M. et al. (2021). Contraceptive progestins with androgenic properties stimulate breast epithelial cell proliferation. **EMBO Molecular Medicine**. https://doi.org/10.15252/emmm.202114314 📗

#. Shi, L. et al. (2021). A KRAS-responsive long non-coding RNA controls microRNA processing. **Nature Communications**. https://doi.org/10.1038/s41467-021-22337-3 😞

#. Shinde-Jadhav, S. et al. (2021). Role of neutrophil extracellular traps in radiation resistance of invasive bladder cancer. **Nature Communications**. https://doi.org/10.1038/s41467-021-23086-z 📗

#. Shinizu, Y. et al. (2021). Exposure to Maternal Immune Activation Causes Congenital Unfolded Protein Response Defects and Increases the Susceptibility to Postnatal Inflammatory Stimulation in Offspring. **Journal of Inflammation Research**. https://doi.org/10.2147/JIR.S294238 📗

#. Shochet, G. E. et al. (2021). Hypoxia Inducible Factor 1A Supports a Pro-Fibrotic Phenotype Loop in Idiopathic Pulmonary Fibrosis. **International Journal of Molecular Sciences**. https://doi.org/10.3390/ijms22073331 📗

#. Siddiqui, Z. et al. (2021). Angiogenic Hydrogels for Dental Pulp Revascularization. **Acta Biomaterialia**. https://doi.org/10.1016/j.actbio.2021.03.001 📗

#. Siddiqui, Z. et al. (2021). Self-assembling peptide hydrogels facilitate vascularization in two-component scaffolds. **Chemical Engineering Journal**. https://doi.org/10.1016/j.cej.2021.130145 😞

#. Siegert, E. et al. (2021). Systemic sclerosis-associated myositis features minimal inflammation and characteristic capillary pathology. **Acta Neuropathologica**. https://doi.org/10.1007/s00401-021-02305-3 📗

#. Silva, B. A. et al. (2021). A thalamo-amygdalar circuit underlying the extinction of remote fear memories. **Nature Neuroscience**. https://doi.org/10.1038/s41593-021-00856-y 📗

#. Simon-Soro, A. et al. (2021). Impact of the repurposed drug thonzonium bromide on host oral-gut microbiomes. **npj Biofilms and Microbiomes**. https://doi.org/10.1038/s41522-020-00181-5 📗

#. Sonntag, T. et al. (2021). Distribution of Gold Nanoparticles in the Anterior Chamber of the Eye after Intracameral Injection for Glaucoma Therapy. **Pharmaceutics**. https://doi.org/10.3390/pharmaceutics13060901 😞

#. Stockton, J. D. et al. (2021). Complete response to neoadjuvant chemoradiotherapy in rectal cancer is associated with RAS/AKT mutations and high tumour mutational burden. **Radiation Oncology**. https://doi.org/10.1186/s13014-021-01853-y 📗

#. Stålhammar, G. et al. (2021). Intratumor Heterogeneity in Uveal Melanoma BAP-1 Expression. **Cancers**. https://doi.org/10.3390/cancers13051143 📗

#. Stępniewski, J. et al. (2021). Human Induced Pluripotent Stem Cell-Derived Cardiomyocytes, in Contrast to Adipose Tissue-Derived Stromal Cells, Efficiently Improve Heart Function in Murine Model of Myocardial Infarction. **Biomedicines**. https://doi.org/10.3390/biomedicines8120578 📗

#. Su, A. L. et al. (2021). _N_-Acetyl-L-cysteine and aminooxyacetic acid differentially modulate trichloroethylene reproductive toxicity via metabolism in Wistar rats. **Achives of Toxicology**. https://doi.org/10.1007/s00204-021-02991-8 📗

#. Su, Y. et al. (2021). CD11c-CD8 Spatial Cross Presentation: A Novel Approach to Link Immune Surveillance and Patient Survival in Soft Tissue Sarcoma. **Cancers**. https://doi.org/10.3390/cancers13051175 📗

#. Sun, Y. et al. (2021). Sensitive and Specific Immunohistochemistry Protocol for Nucleocapsid Protein from All Common SARS-CoV-2 Virus Strains in Formalin-Fixed, Paraffin Embedded Tissues. **Methods and Protocols**. https://doi.org/10.3390/mps4030047 😞

#. Sun, Z. et al. (2021). Developing an enhanced 7-color multiplex IHC protocol to dissect immune infiltration in human cancers. **PLOS ONE**. https://doi.org/10.1371/journal.pone.0247238 📗

#. Suurs, F. V. et al. (2021). Mesothelin/CD3 half-life extended bispecific T-cell engager molecule shows specific tumor uptake and distributes to mesothelin and CD3 expressing tissues. **Journal of Nuclear Medicine**. https://doi-org.ezproxy.is.ed.ac.uk/10.2967/jnumed.120.259036 📗

#. Tahkola, K. et al. (2021). Stromal hyaluronan accumulation is associated with low immune response and poor prognosis in pancreatic cancer. **Scientific Reports**. https://doi.org/10.1038/s41598-021-91796-x 📗

#. Tang, Y. et al. (2021). GANDA: A deep generative adversarial network conditionally generates intratumoral nanoparticles distribution pixels-to-pixels. **Journal of Controlled Release**. https://doi.org/10.1016/j.jconrel.2021.06.039 📗

#. Tavernari, D. et al. (2021). Nongenetic Evolution Drives Lung Adenocarcinoma Spatial Heterogeneity and Progression. **Cancer Discovery**. https://doi.org/10.1158/2159-8290.CD-20-1274 📗

#. Tran, V.-L. et al. (2021). Quantitative Tissue Pharmacokinetics and EPR Effect of AGuIX Nanoparticles: A Multimodal Imaging Study in an Orthotopic Glioblastoma Rat Model and Healthy Macaque. **Advanced Healthcare Materials**. https://doi.org/10.1002/adhm.202100656 😞

#. Trinh, A. et al. (2021). Genomic Alterations during the *In Situ* to Invasive Ductal Breast Carcinoma Transition Shaped by the Immune System. **Molecular Cancer Research**. https://doi.org/10.1158/1541-7786.MCR-20-0949 📗

#. Tulotta, C. et al. (2021). IL-1B drives opposing responses in primary tumours and bone metastases; harnessing combination therapies to improve outcome in breast cancer. **npj Breast Cancer**. https://doi.org/10.1038/s41523-021-00305-w 📗

#. Van Hove, L. et al. (2021). Fibrotic enzymes modulate wound‐induced skin tumorigenesis. **EMBO Reports**. https://doi.org/10.15252/embr.202051573 😞

#. Van Neerven, S. M. et al. (2021). _Apc_-mutant cells act as supercompetitors in intestinal tumour initiation. **Nature**. https://doi.org/10.1038/s41586-021-03558-4 📗

#. Van Olst, L. et al. (2021). Meningeal inflammation in multiple sclerosis induces phenotypic changes in cortical microglia that differentially associate with neurodegeneration. **Acta Neuropathologica**. https://doi.org/10.1007/s00401-021-02293-4 📗

#. Vankerckhoven, A. et al. (2021). Type of chemotherapy has substantial effects on the immune system in ovarian cancer. **Translational Oncology**. https://doi.org/10.1016/j.tranon.2021.101076 📗

#. Varese, A. et al. (2021). Extracellular acidosis enhances Zika virus infection both in human cells and ex vivo tissue cultures from female reproductive tract. **Emerging Microbes & Infections**. https://doi.org/10.1080/22221751.2021.1932606 😞

#. Vassileva, V. et al. (2021). Effective Detection and Monitoring of Glioma Using [18F]FPIA PET Imaging. **Biomedicines**. https://doi.org/10.3390/biomedicines9070811 📗

#. Victoor, J. et al. (2021). Comprehensive immunomolecular profiling of endometrial carcinoma: A tertiary retrospective study. **Gynecologic Oncology**. https://doi.org/10.1016/j.ygyno.2021.06.030 📗

#. Vishnyakova, P. et al. (2021). Preeclampsia: inflammatory signature of decidual cells in early manifestation of disease. **Placenta**. https://doi.org/10.1016/j.placenta.2021.01.011 📗

#. Voggel, J. et al. (2021). Vascular tone regulation in renal interlobar arteries of male rats is dysfunctional after intrauterine growth restriction. **American Journal of Physiology**. https://doi.org/10.1152/ajprenal.00653.2020 📗

#. Wan, C. et al. (2021). Genome-scale CRISPR-Cas9 screen of Wnt/β-catenin signaling identifies therapeutic targets for colorectal cancer. **Science Advances**. https://doi.org/10.1126/sciadv.abf2567 😞

#. Wang, A. et al. (2021). Cytokine RNA in situ hybridization permits individualized molecular phenotyping in biopsies of psoriasis and atopic dermatitis. **JID Innovations**. https://doi.org/10.1016/j.xjidi.2021.100021 📗

#. Wang, X. et al. (2021). White button mushroom (Agaricus bisporus) disrupts androgen receptor signaling in human prostate cancer cells and patient-derived xenograft. **The Journal of Nutritional Biochemistry**. https://doi.org/10.1016/j.jnutbio.2020.108580 😞

#. Wang, Z. et al. (2021). Disruption of the HER3-PI3K-mTOR oncogenic signaling axis and PD-1 blockade as a multimodal precision immunotherapy in head and neck cancer. **Nature Communications**. https://doi.org/10.1038/s41467-021-22619-w 📗

#. We, J. et al. (2021). Validation of multiplex immunofluorescence and digital image analysis for programmed death-ligand 1 expression and immune cell assessment in non-small cell lung cancer: comparison with conventional immunohistochemistry. **Journal of Clinical Pathology**. http://dx.doi.org/10.1136/jclinpath-2021-207448 📗

#. Wei, S. C. et al. (2021). A Genetic Mouse Model Recapitulates Immune Checkpoint Inhibitor-Associated Myocarditis and Supports a Mechanism-Based Therapeutic Intervention. **Cancer Discovery**. https://doi.org/10.1158/2159-8290.cd-20-0856 📗

#. Weiner, A. B. et al. (2021). Plasma cells are enriched in localized prostate cancer in Black men and are associated with improved outcomes. **Nature Communications**. https://doi.org/10.1038/s41467-021-21245-w 📗

#. Werner, F. et al. (2021). A Standardized Analysis of Tertiary Lymphoid Structures in Human Melanoma: Disease Progression- and Tumor Site-Associated Changes With Germinal Center Alteration. **Frontiers in Immunology**. https://doi.org/10.3389/fimmu.2021.675146 📗

#. Weyerer, V. et al. (2021). Prognostic impact of molecular muscle‐invasive bladder cancer subtyping approaches and correlations with variant histology in a population‐based mono‐institutional cystectomy cohort. **World Journal of Urology**. https://doi.org/10.1007/s00345-021-03788-1 😞

#. Williams, A. et al. (2021). Higher Number of EBI3 Cells in Mucosal Chronic Hyperplastic Candidiasis May Serve to Regulate IL-17-Producing Cells. **Journal of Fungi**. https://doi.org/10.3390/jof7070533 📗

#. Williamson, T. et al. (2021). Mebendazole disrupts stromal desmoplasia and tumorigenesis in two models of pancreatic cancer. **Oncotarget**. https://doi.org/10.18632/oncotarget.28014 📗

#. Wingerter, A. et al. (2021). Exploiting Gangliosides for the Therapy of Ewing’s Sarcoma and H3K27M-Mutant Diffuse Midline Glioma. **Cancers**. https://doi.org/10.3390/cancers13030520 📗

#. Won, J-S. et al. (2021). Optimal Preclinical Conditions for Using Adult Human Multipotent Neural Cells in the Treatment of Spinal Cord Injury. **International Journal of Molecular Sciences**. https://doi.org/10.3390/ijms22052579 📗

#. Xia, Y. et al. (2021). Immune and repair responses in joint tissues and lymphnodes after knee arthroplasty surgery in mice. **Journal of Bone and Mineral Research**. https://doi.org/10.1002/jbmr.4381 📗

#. Xu, D. et al. (2021). Malignant pleural mesothelioma co-opts BCL-X<sub>L</sub> and autophagy to escape apoptosis. **Cell Death & Disease**. https://doi.org/10.1038/s41419-021-03668-x 📗

#. Yoon, S-H. et al. (2021). Preoperative immune landscape predisposes adverse outcomes in hepatocellular carcinoma patients with liver transplantation. **npj Precision Oncology**. https://doi.org/10.1038/s41698-021-00167-2 📗

#. Zacarías-Fluck, M. F. et al. (2021). The Wnt signaling receptor Fzd9 is essential for Myc-driven tumorigenesis in pancreatic islets. **Life Science Alliance**. https://doi.org/10.26508/lsa.201900490 📗

#. Zhang, N. et al. (2021). Electrophysiologic and Morphologic Strain Differences in a Low-Dose NaIO3-Induced Retinal Pigment Epithelium Damage Model. **Translational Vision Science & Technology**. https://doi.org/10.1167/tvst.10.8.10 📗

#. Zhang, Y. et al. (2021). Patch test relevant concentrations of metal salts cause localized cytotoxicity, including apoptosis, in skin *ex vivo*. **Contact Dermatitis**. https://doi.org/10.1111/cod.13940 😞

#. Zhao, P. et al. (2021). Efficacy of AAV9-mediated SGPL1 gene transfer in a mouse model of S1P lyase insufficiency syndrome. **JCI Insight**. https://doi.org/10.1172/jci.insight.145936 😞

#. Zhou, G. et al. (2021). Silica nanoparticles inducing the apoptosis via microRNA-450b-3p targeting MTCH2 in mice and spermatocyte cell. **Environmental Pollution**. https://doi.org/10.1016/j.envpol.2021.116771 😞

#. Zhou, J. et al. (2021). Orphan nuclear receptor TLX promotes immunosuppression via its transcriptional activation of PD-L1 in glioma. **Journal for ImmunoTherapy of Cancer**. http://dx.doi.org/10.1136/jitc-2020-001937 😞

#. Zoupi, L. et al. (2021). Selective vulnerability of inhibitory networks in multiple sclerosis. **Acta Neuropathologica**. https://doi.org/10.1007/s00401-020-02258-z 📗

#. van Neeren, S. M. et al. (2021). _Apc_-mutant cells act as supercompetitors in intestinal tumour initiation. **Nature**. https://doi.org/10.1038/s41586-021-03558-4 📗

#. von Hagen, F. et al. (2021). N\ :sup:`6`\ ‐Methyladenosine (m\ :sup:`6`\ A) readers are dysregulated in renal cell carcinoma. **Molecular Carcinogenesis**. https://doi.org/10.1002/mc.23297 📗
